# Background and Foreground
background #0f111a
foreground #8f93a2

# Black
color0 #2e3436
color8 #2e3436

# Red
color1 #ff5370
color9 #ff5370

# Green
color2 #c3e88d
color10 #c3e88d

# Yellow
color3 #ffcb6b
color11 #ffcb6b

# Blue
color4 #82aaff
color12 #82aaff

# Magenta
color5 #c792ea
color13 #c792ea

# Cyan
color6 #89ddff
color14 #89ddff

# White
color7 #dcdfe4
color15 #dcdfe4



background_opacity 0.75


#from banakai testing 