[project]
name = "bankai"
version = "1.1.1"
description = "TUI to help you setup your Linux system"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "rich",
]

[project.optional-dependencies]
test = ["pytest"]

[tool.pytest.ini_options]
pythonpath = [
    ".",
]

[project.scripts]
bankai = "bankai:main"

[tool.setuptools]
py-modules = ["bankai"]
packages = ["os_scripts", "common", "configs"]
include-package-data = true

[dependency-groups]
dev = [
    "pytest>=9.0.1",
]
 