import { afterEach, beforeEach, describe, expect, it } from "bun:test";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";

import { runCommandCapture } from "../src/common/utils.js";
import * as migration from "../src/helpers/migrate_omarchy_3_to_4.js";
import { configureOmarchyWorkspaces } from "../src/helpers/configure_omarchy_workspaces.js";

const STOCK_MONITORS_LUA = `-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
-- List current monitors and supported resolutions with: hyprctl monitors all

local omarchy_gdk_scale = 2
local omarchy_monitor_scale = "auto"

hl.env("GDK_SCALE", tostring(omarchy_gdk_scale))
hl.monitor({ output = "", mode = "preferred", position = "auto", scale = omarchy_monitor_scale })

-- Configure a specific monitor.
-- hl.monitor({ output = "DP-2", mode = "2560x1440@144", position = "0x0", scale = 1 })

-- Portrait/rotated secondary monitor (transform: 1 = 90°, 3 = 270°).
-- hl.monitor({ output = "DP-2", mode = "preferred", position = "auto", scale = 1, transform = 1 })
`;

describe("migrateOmarchy3To4", () => {
	let home;

	function runAccepted(overrides = {}) {
		return migration.migrateOmarchy3To4?.({
			home,
			now: () => 42,
			env: {},
			captureCommandImpl: async (command) => {
				if (command === "omarchy version") {
					return {
						exitCode: 0,
						stdout: "Omarchy 4.0.0\n",
						stderr: "",
						failed: false,
					};
				}
				if (command === "hyprctl configerrors") {
					return { exitCode: 0, stdout: "", stderr: "", failed: false };
				}
				throw new Error(`unexpected ${command}`);
			},
			runCommandImpl: async () => true,
			configureOmarchyWorkspacesImpl: async () => ({}),
			configureHyprmoncfgImpl: async () => {
				const monitors = path.join(
					home,
					".config",
					"hypr",
					"monitors.lua",
				);
				if (!fs.existsSync(monitors)) {
					fs.mkdirSync(path.dirname(monitors), { recursive: true });
					fs.writeFileSync(monitors, "-- Generated by hyprmoncfg\nreturn {}\n");
				}
				return {
					deployed: 0,
					packageReady: true,
					serviceEnabled: true,
				};
			},
			configureOmarchyPluginsImpl: async () => ({
				manualAuthChecklist: [],
				failed: [],
			}),
			configureOmarchyBarImpl: async () => ({
				status: "configured",
				changed: false,
			}),
			sleepImpl: async () => {
				const monitors = path.join(
					home,
					".config",
					"hypr",
					"monitors.lua",
				);
				if (!fs.existsSync(monitors)) {
					fs.mkdirSync(path.dirname(monitors), { recursive: true });
					fs.writeFileSync(monitors, "-- Generated by hyprmoncfg\nreturn {}\n");
				}
			},
			...overrides,
		});
	}

	beforeEach(() => {
		home = fs.mkdtempSync(path.join(os.tmpdir(), "haoshoku-o4-migration-"));
	});

	afterEach(() => {
		fs.rmSync(home, { recursive: true, force: true });
	});

	it("refuses Omarchy versions below 4 without running a later step", async () => {
		const laterCalls = [];
		const result = await migration.migrateOmarchy3To4?.({
			home,
			captureCommandImpl: async (command) => {
				if (command !== "omarchy version")
					throw new Error(`unexpected ${command}`);
				return {
					exitCode: 0,
					stdout: "Omarchy 3.8.5\n",
					stderr: "",
					failed: false,
				};
			},
			configureOmarchyWorkspacesImpl: async () => laterCalls.push("workspaces"),
			configureHyprmoncfgImpl: async () => laterCalls.push("hyprmoncfg"),
			configureOmarchyPluginsImpl: async () => laterCalls.push("plugins"),
			runCommandImpl: async (command) => laterCalls.push(command),
		});

		expect(result?.status).toBe("refused");
		expect(result?.steps).toEqual([
			expect.objectContaining({
				name: "version gate",
				status: "refused",
				message: expect.stringContaining("Omarchy 4 or newer"),
			}),
		]);
		expect(laterCalls).toEqual([]);
	});

	it("accepts a parseable Omarchy major version at or above 4", async () => {
		const result = await runAccepted({
			captureCommandImpl: async (command) => ({
				exitCode: 0,
				stdout: command === "omarchy version" ? "Omarchy 4.0.0\n" : "",
				stderr: "",
				failed: false,
			}),
		});

		expect(result?.status).not.toBe("refused");
		expect(result?.steps?.[0]).toEqual({
			name: "version gate",
			status: "clean",
			major: 4,
		});
	});

	it("refuses missing or unparsable version output", async () => {
		for (const versionResult of [
			{ exitCode: 127, stdout: "", stderr: "missing", failed: true },
			{
				exitCode: 0,
				stdout: "Omarchy development build\n",
				stderr: "",
				failed: false,
			},
		]) {
			const result = await migration.migrateOmarchy3To4?.({
				home,
				captureCommandImpl: async () => versionResult,
			});
			expect(result?.status).toBe("refused");
		}
	});

	it("treats an absent or unrelated hyprland.conf as already done", async () => {
		for (const content of [null, "source = ~/.config/hypr/foreign.conf\n"]) {
			const legacy = path.join(home, ".config", "hypr", "hyprland.conf");
			fs.rmSync(path.dirname(legacy), { recursive: true, force: true });
			if (content !== null) {
				fs.mkdirSync(path.dirname(legacy), { recursive: true });
				fs.writeFileSync(legacy, content);
			}

			const result = await runAccepted();
			expect(result?.steps?.[1]).toEqual({
				name: "legacy source cleanup",
				status: "already done",
			});
			expect(
				fs.existsSync(`${legacy}.bak.42`) ||
					fs.existsSync(`${legacy}.bak.42.1`),
			).toBe(false);
		}
	});

	it("atomically removes only Haoshoku source lines after a collision-safe backup", async () => {
		const legacy = path.join(home, ".config", "hypr", "hyprland.conf");
		fs.mkdirSync(path.dirname(legacy), { recursive: true });
		const original = [
			"source = ~/.config/hypr/foreign.conf",
			"  source=~/.config/hypr/haoshoku-bindings.conf  ",
			"source = /home/example/.config/hypr/haoshoku-workspaces.conf",
			"# source = ~/.config/hypr/haoshoku-commented.conf",
			"",
		].join("\n");
		fs.writeFileSync(legacy, original);
		fs.writeFileSync(`${legacy}.bak.42`, "existing collision\n");
		const writes = [];
		const fsImpl = {
			...fs,
			writeFileSync(file, ...args) {
				writes.push(file);
				return fs.writeFileSync(file, ...args);
			},
		};

		const result = await runAccepted({ fsImpl });

		expect(result?.steps?.[1]).toEqual(
			expect.objectContaining({
				name: "legacy source cleanup",
				status: "applied",
				backup: `${legacy}.bak.42.1`,
			}),
		);
		expect(fs.readFileSync(legacy, "utf8")).toBe(
			"source = ~/.config/hypr/foreign.conf\n# source = ~/.config/hypr/haoshoku-commented.conf\n",
		);
		expect(fs.readFileSync(`${legacy}.bak.42.1`, "utf8")).toBe(original);
		expect(writes).not.toContain(legacy);
		expect(writes).not.toContain(`${legacy}.bak.42.1`);
	});

	it("backs up and removes unmarked orphans while preserving owned monitors.conf", async () => {
		const hypr = path.join(home, ".config", "hypr");
		fs.mkdirSync(hypr, { recursive: true });
		const bindings = path.join(hypr, "haoshoku-bindings.conf");
		const workspaces = path.join(hypr, "haoshoku-workspaces.conf");
		const monitors = path.join(hypr, "monitors.conf");
		fs.writeFileSync(bindings, "legacy bindings\n");
		fs.writeFileSync(workspaces, "legacy workspaces\n");
		fs.writeFileSync(
			monitors,
			"\uFEFF# Generated by hyprmoncfg\r\nmonitor=owned\r\n",
		);

		const result = await runAccepted();

		expect(result?.steps?.[2]).toEqual(
			expect.objectContaining({ name: "orphan cleanup", status: "applied" }),
		);
		expect(fs.existsSync(bindings)).toBe(false);
		expect(fs.existsSync(workspaces)).toBe(false);
		expect(fs.readFileSync(`${bindings}.bak.42`, "utf8")).toBe(
			"legacy bindings\n",
		);
		expect(fs.readFileSync(`${workspaces}.bak.42`, "utf8")).toBe(
			"legacy workspaces\n",
		);
		expect(fs.readFileSync(monitors, "utf8")).toContain(
			"# Generated by hyprmoncfg",
		);
		expect(fs.existsSync(`${monitors}.bak.42`)).toBe(false);
	});

	it("recognizes only exact hyprmoncfg first-line markers", async () => {
		const hypr = path.join(home, ".config", "hypr");
		const monitors = path.join(hypr, "monitors.conf");
		for (const marker of [
			"\uFEFF# Generated by hyprmoncfg\r\nmonitor=owned\r\n",
			"-- Generated by hyprmoncfg\nmonitor=owned\n",
		]) {
			fs.rmSync(hypr, { recursive: true, force: true });
			fs.mkdirSync(hypr, { recursive: true });
			fs.writeFileSync(monitors, marker);
			const result = await runAccepted();
			expect(result?.steps?.[2]?.status).toBe("already done");
			expect(fs.existsSync(monitors)).toBe(true);
		}

		fs.writeFileSync(
			monitors,
			"# customized\n# Generated by hyprmoncfg\nmonitor=unmanaged\n",
		);
		const result = await runAccepted();
		expect(result?.steps?.[2]?.status).toBe("applied");
		expect(fs.existsSync(monitors)).toBe(false);
		expect(fs.readFileSync(`${monitors}.bak.42`, "utf8")).toContain(
			"monitor=unmanaged",
		);
	});

	it("treats missing live theme files as already done", async () => {
		const result = await runAccepted();

		expect(result?.steps?.[3]).toEqual(
			expect.objectContaining({
				name: "live theme paths",
				status: "already done",
			}),
		);
	});

	it("atomically rewrites live fish and session paths only once", async () => {
		const fish = path.join(home, ".config", "fish", "config.fish");
		const kitty = path.join(home, ".config", "kitty");
		const haki = path.join(kitty, "haki.session");
		const agents = path.join(kitty, "agents.session");
		const kittyConf = path.join(kitty, "kitty.conf");
		fs.mkdirSync(path.dirname(fish), { recursive: true });
		fs.mkdirSync(kitty, { recursive: true });
		fs.writeFileSync(
			fish,
			"set theme ~/.config/omarchy/current/theme\nset icon ~/.config/omarchy/current/icon\n",
		);
		fs.writeFileSync(haki, "cd ~/.config/omarchy/current\n");
		fs.writeFileSync(agents, "cd ~/.local/state/omarchy/current\n");
		fs.writeFileSync(
			kittyConf,
			"include ~/.config/omarchy/current/kitty.conf\n",
		);
		const writes = [];
		const renames = [];
		const fsImpl = {
			...fs,
			writeFileSync(file, ...args) {
				writes.push(file);
				return fs.writeFileSync(file, ...args);
			},
			renameSync(from, to) {
				renames.push({ from, to });
				return fs.renameSync(from, to);
			},
		};

		const first = await runAccepted({ fsImpl });

		expect(first?.steps?.[3]?.status).toBe("applied");
		expect(fs.readFileSync(fish, "utf8")).toBe(
			"set theme ~/.local/state/omarchy/current/theme\nset icon ~/.local/state/omarchy/current/icon\n",
		);
		expect(fs.readFileSync(haki, "utf8")).toBe(
			"cd ~/.local/state/omarchy/current\n",
		);
		expect(fs.readFileSync(agents, "utf8")).toBe(
			"cd ~/.local/state/omarchy/current\n",
		);
		expect(fs.readFileSync(kittyConf, "utf8")).toContain(
			"~/.config/omarchy/current",
		);
		expect(writes).not.toEqual(expect.arrayContaining([fish, haki, agents]));
		expect(renames.map(({ to }) => to)).toEqual(
			expect.arrayContaining([fish, haki, `${fish}.bak.42`, `${haki}.bak.42`]),
		);

		writes.length = 0;
		renames.length = 0;
		const second = await runAccepted({ fsImpl });
		expect(second?.steps?.[3]?.status).toBe("already done");
		expect(writes).toEqual([]);
		expect(renames).toEqual([]);
		expect(fs.existsSync(`${fish}.bak.42.1`)).toBe(false);
		expect(fs.existsSync(`${haki}.bak.42.1`)).toBe(false);
	});

	it("treats absent or hyprmoncfg-owned monitors.lua as already done", async () => {
		const monitors = path.join(home, ".config", "hypr", "monitors.lua");
		for (const content of [
			null,
			"\uFEFF-- Generated by hyprmoncfg\r\nreturn {}\r\n",
		]) {
			fs.rmSync(path.dirname(monitors), { recursive: true, force: true });
			if (content !== null) {
				fs.mkdirSync(path.dirname(monitors), { recursive: true });
				fs.writeFileSync(monitors, content);
			}
			const result = await runAccepted();
			expect(
				result?.steps?.find(
					(step) => step.name === "monitors.lua ownership handoff",
				)?.status,
			).toBe("already done");
			if (content !== null) expect(fs.existsSync(monitors)).toBe(true);
		}
	});

	it("backs up the exact Omarchy v4 stock monitors.lua and waits for its managed replacement", async () => {
		const monitors = path.join(home, ".config", "hypr", "monitors.lua");
		fs.mkdirSync(path.dirname(monitors), { recursive: true });
		fs.writeFileSync(monitors, STOCK_MONITORS_LUA);

		const result = await runAccepted();

		expect(
			result?.steps?.find(
				(step) => step.name === "monitors.lua ownership handoff",
			),
		).toEqual(
			expect.objectContaining({
				name: "monitors.lua ownership handoff",
				status: "applied",
				backup: `${monitors}.bak.42`,
			}),
		);
		expect(fs.readFileSync(monitors, "utf8")).toStartWith(
			"-- Generated by hyprmoncfg",
		);
		expect(fs.readFileSync(`${monitors}.bak.42`, "utf8")).toBe(
			STOCK_MONITORS_LUA,
		);
	});

	it("backs up customized monitors.lua once and loudly leaves manual attention unresolved", async () => {
		const monitors = path.join(home, ".config", "hypr", "monitors.lua");
		fs.mkdirSync(path.dirname(monitors), { recursive: true });
		const customized =
			'-- My hand-tuned monitor layout\nhl.monitor({ output = "DP-9" })\n';
		fs.writeFileSync(monitors, customized);
		const warnings = [];
		const logImpl = {
			info() {},
			success() {},
			warning(message) {
				warnings.push(message);
			},
			error(message) {
				warnings.push(message);
			},
			dim() {},
		};

		const first = await runAccepted({ logImpl });
		expect(
			first?.steps?.find(
				(step) => step.name === "monitors.lua ownership handoff",
			),
		).toEqual(
			expect.objectContaining({
				status: "manual attention",
				backup: `${monitors}.bak.42`,
				message: expect.stringContaining("hyprmoncfg will refuse"),
			}),
		);
		expect(first?.status).toBe("manual attention");
		expect(fs.readFileSync(monitors, "utf8")).toBe(customized);
		expect(fs.readFileSync(`${monitors}.bak.42`, "utf8")).toBe(customized);

		const second = await runAccepted({ logImpl });
		expect(
			second?.steps?.find(
				(step) => step.name === "monitors.lua ownership handoff",
			)?.status,
		).toBe("manual attention");
		expect(fs.existsSync(`${monitors}.bak.42.1`)).toBe(false);
		expect(
			warnings.filter((message) => message.includes("manual attention")),
		).toHaveLength(2);
	});

	it("delegates reusable configuration in order and preserves structured plugin failures", async () => {
		const calls = [];
		const pluginResult = {
			installed: ["ready"],
			enabled: [],
			alreadyReady: [],
			failed: ["broken"],
			manualAuthChecklist: [
				{ id: "ready", requirement: "sign in after installation" },
			],
		};
		const result = await runAccepted({
			configureOmarchyWorkspacesImpl: async ({ home: configuredHome }) => {
				if (configuredHome !== home) throw new Error("wrong workspace home");
				calls.push("workspaces");
				return { bindingsChanged: true, sourceChanged: true };
			},
			configureHyprmoncfgImpl: async ({ home: configuredHome }) => {
				if (configuredHome !== home) throw new Error("wrong hyprmoncfg home");
				calls.push("hyprmoncfg");
				return { deployed: 1, packageReady: true, serviceEnabled: true };
			},
			configureOmarchyPluginsImpl: async () => {
				calls.push("plugins");
				return pluginResult;
			},
			configureOmarchyBarImpl: async ({ home: configuredHome }) => {
				if (configuredHome !== home) throw new Error("wrong bar home");
				calls.push("bar");
				return { status: "configured", changed: true };
			},
		});

		expect(calls).toEqual(["workspaces", "hyprmoncfg", "plugins", "bar"]);
		expect(
			result?.steps?.find((step) => step.name === "deploy reusable config"),
		).toEqual({
			name: "deploy reusable config",
			status: "applied",
			workspaces: { bindingsChanged: true, sourceChanged: true },
			hyprmoncfg: {
				deployed: 1,
				packageReady: true,
				serviceEnabled: true,
			},
		});
		expect(result?.steps?.find((step) => step.name === "plugins")).toEqual({
			name: "plugins",
			status: "manual attention",
			result: pluginResult,
		});
		expect(result?.steps?.find((step) => step.name === "bar")).toEqual({
			name: "bar",
			status: "applied",
			result: { status: "configured", changed: true },
		});
		expect(result?.manualAuthChecklist).toEqual(
			pluginResult.manualAuthChecklist,
		);
	});

	it("records a bar deployment exception as failed but still validates", async () => {
		const calls = [];
		const result = await runAccepted({
			configureOmarchyPluginsImpl: async () => {
				calls.push("plugins");
				return { manualAuthChecklist: [], failed: [] };
			},
			configureOmarchyBarImpl: async () => {
				calls.push("bar");
				throw new Error("bar deployment exploded");
			},
			runCommandImpl: async (command) => {
				calls.push(command);
				return true;
			},
		});

		expect(calls).toEqual(["plugins", "bar", "hyprctl reload"]);
		expect(result?.steps?.find((step) => step.name === "bar")).toEqual(
			expect.objectContaining({
				name: "bar",
				status: "failed",
				message: expect.stringContaining("bar deployment exploded"),
			}),
		);
		expect(
			result?.steps?.find((step) => step.name === "validate and hand off")?.status,
		).toBe("clean");
		expect(result?.status).toBe("failed");
	});

	it("promotes disableOnInstall failures to manual attention", async () => {
		const result = await runAccepted({
			configureOmarchyPluginsImpl: async () => ({
				installed: [],
				enabled: [],
				alreadyReady: [],
				configured: [],
				failed: [],
				configureFailed: [
					{
						id: "replacement",
						action: "disable",
						targetId: "omarchy.stock-widget",
					},
				],
				manualAuthChecklist: [],
			}),
		});

		expect(result?.steps?.find((step) => step.name === "plugins")?.status).toBe(
			"manual attention",
		);
		expect(result?.status).toBe("manual attention");
	});

	it("promotes skipped plugin reconciliation to manual attention", async () => {
		const result = await runAccepted({
			configureOmarchyPluginsImpl: async () => ({
				snapshotUnavailable: true,
				installed: [],
				enabled: [],
				alreadyReady: [],
				configured: [],
				failed: [],
				configureFailed: [],
				manualAuthChecklist: [],
			}),
		});

		expect(result?.steps?.find((step) => step.name === "plugins")?.status).toBe(
			"manual attention",
		);
		expect(result?.status).toBe("manual attention");
	});

	it("keeps all-empty plugin failure summaries already done", async () => {
		const result = await runAccepted({
			configureOmarchyPluginsImpl: async () => ({
				snapshotUnavailable: false,
				installed: [],
				enabled: [],
				alreadyReady: [],
				configured: [],
				failed: [],
				configureFailed: [],
				manualAuthChecklist: [],
			}),
		});

		expect(result?.steps?.find((step) => step.name === "plugins")?.status).toBe(
			"already done",
		);
		expect(result?.status).toBe("completed");
	});

	it("returns structured recovery when hyprmoncfg throws after workspace requires are appended", async () => {
		const hypr = path.join(home, ".config", "hypr");
		const main = path.join(hypr, "hyprland.lua");
		fs.mkdirSync(hypr, { recursive: true });
		fs.writeFileSync(main, 'require("hypr.defaults")\n');
		const externalCalls = [];
		const messages = [];

		const result = await runAccepted({
			configureOmarchyWorkspacesImpl: configureOmarchyWorkspaces,
			configureHyprmoncfgImpl: async () => {
				throw new Error("hyprmoncfg package install exploded");
			},
			configureOmarchyPluginsImpl: async () => {
				externalCalls.push("plugins");
				return { manualAuthChecklist: [], failed: [] };
			},
			captureCommandImpl: async (command) => {
				externalCalls.push(command);
				if (command === "omarchy version") {
					return {
						exitCode: 0,
						stdout: "Omarchy 4.0.0\n",
						stderr: "",
						failed: false,
					};
				}
				throw new Error(`unexpected ${command}`);
			},
			runCommandImpl: async (command) => {
				externalCalls.push(command);
				return true;
			},
			logImpl: {
				info: (message) => messages.push(message),
				success: (message) => messages.push(message),
				warning: (message) => messages.push(message),
				error: (message) => messages.push(message),
				dim() {},
			},
		});

		expect(result?.status).toBe("failed");
		expect(result?.steps.map(({ name }) => name)).toEqual([
			"version gate",
			"legacy source cleanup",
			"orphan cleanup",
			"live theme paths",
			"deploy reusable config",
			"plugins",
			"bar",
			"validate and hand off",
		]);
		expect(
			result?.steps?.find((step) => step.name === "deploy reusable config"),
		).toEqual(
			expect.objectContaining({
				name: "deploy reusable config",
				status: "failed",
				workspaces: expect.objectContaining({ sourceChanged: true }),
				hyprmoncfg: expect.objectContaining({
					status: "failed",
					message: expect.stringContaining("package install exploded"),
				}),
			}),
		);
		expect(result?.steps?.find((step) => step.name === "plugins")?.status).toBe(
			"skipped",
		);
		expect(
			result?.steps?.find((step) => step.name === "validate and hand off")
				?.status,
		).toBe("skipped");
		expect(externalCalls).toEqual(["omarchy version"]);
		expect(fs.readFileSync(main, "utf8")).toContain(
			'require("hypr.haoshoku.bindings")',
		);
		expect(result?.recoveryInstruction).toBe(
			"remove the appended require lines from hyprland.lua, then reboot",
		);
		expect(
			messages.filter((message) => message === result.recoveryInstruction),
		).toHaveLength(1);
	});

	it("returns structured recovery when workspace deployment throws after partial mutation", async () => {
		const main = path.join(home, ".config", "hypr", "hyprland.lua");
		fs.mkdirSync(path.dirname(main), { recursive: true });
		fs.writeFileSync(main, 'require("hypr.defaults")\n');
		const helperCalls = [];
		const messages = [];

		const result = await runAccepted({
			configureOmarchyWorkspacesImpl: async () => {
				fs.appendFileSync(main, 'require("hypr.haoshoku.bindings")\n');
				throw new Error("workspace deployment exploded");
			},
			configureHyprmoncfgImpl: async () => {
				helperCalls.push("hyprmoncfg");
				return { deployed: 0, packageReady: true, serviceEnabled: true };
			},
			configureOmarchyPluginsImpl: async () => {
				helperCalls.push("plugins");
				return { manualAuthChecklist: [], failed: [] };
			},
			runCommandImpl: async (command) => {
				helperCalls.push(command);
				return true;
			},
			logImpl: {
				info: (message) => messages.push(message),
				success() {},
				warning: (message) => messages.push(message),
				error: (message) => messages.push(message),
				dim() {},
			},
		});

		expect(result?.status).toBe("failed");
		expect(result?.steps).toHaveLength(8);
		expect(
			result?.steps?.find((step) => step.name === "deploy reusable config"),
		).toEqual(
			expect.objectContaining({
				name: "deploy reusable config",
				status: "failed",
				workspaces: expect.objectContaining({
					status: "failed",
					message: expect.stringContaining("workspace deployment exploded"),
				}),
				hyprmoncfg: expect.objectContaining({ status: "skipped" }),
			}),
		);
		expect(result?.steps?.find((step) => step.name === "plugins")?.status).toBe(
			"skipped",
		);
		expect(
			result?.steps?.find((step) => step.name === "validate and hand off")
				?.status,
		).toBe("skipped");
		expect(helperCalls).toEqual([]);
		expect(fs.readFileSync(main, "utf8")).toContain(
			'require("hypr.haoshoku.bindings")',
		);
		expect(
			messages.filter((message) => message === result.recoveryInstruction),
		).toHaveLength(1);
	});

	it("returns structured recovery when plugin deployment throws", async () => {
		const externalCalls = [];
		const messages = [];
		const result = await runAccepted({
			configureOmarchyPluginsImpl: async () => {
				throw new Error("plugin installation exploded");
			},
			captureCommandImpl: async (command) => {
				externalCalls.push(command);
				if (command === "omarchy version") {
					return {
						exitCode: 0,
						stdout: "Omarchy 4.0.0\n",
						stderr: "",
						failed: false,
					};
				}
				throw new Error(`unexpected ${command}`);
			},
			runCommandImpl: async (command) => {
				externalCalls.push(command);
				return true;
			},
			logImpl: {
				info: (message) => messages.push(message),
				success() {},
				warning: (message) => messages.push(message),
				error: (message) => messages.push(message),
				dim() {},
			},
		});

		expect(result?.status).toBe("failed");
		expect(result?.steps).toHaveLength(9);
		expect(result?.steps?.[6]).toEqual(
			expect.objectContaining({
				name: "plugins",
				status: "failed",
				message: expect.stringContaining("plugin installation exploded"),
			}),
		);
		expect(result?.steps?.[7]).toEqual(
			expect.objectContaining({ name: "bar", status: "skipped" }),
		);
		expect(result?.steps?.[8]?.status).toBe("skipped");
		expect(externalCalls).toEqual(["omarchy version"]);
		expect(
			messages.filter((message) => message === result.recoveryInstruction),
		).toHaveLength(1);
	});

	it("reports manual attention when hyprmoncfg readiness fails without a deploy", async () => {
		const result = await runAccepted({
			configureHyprmoncfgImpl: async () => ({
				deployed: 0,
				packageReady: false,
				serviceEnabled: false,
			}),
		});

		expect(
			result?.steps?.find((step) => step.name === "deploy reusable config"),
		).toEqual(
			expect.objectContaining({
				name: "deploy reusable config",
				status: "manual attention",
				message: expect.stringContaining("package and service are not ready"),
			}),
		);
		expect(result?.status).toBe("manual attention");
	});

	it("reports manual attention when a changed hyprmoncfg deploy leaves the service unready", async () => {
		const result = await runAccepted({
			configureHyprmoncfgImpl: async () => ({
				deployed: 1,
				packageReady: true,
				serviceEnabled: false,
			}),
		});

		expect(
			result?.steps?.find((step) => step.name === "deploy reusable config"),
		).toEqual(
			expect.objectContaining({
				status: "manual attention",
				message: expect.stringContaining("service is not ready"),
				hyprmoncfg: {
					deployed: 1,
					packageReady: true,
					serviceEnabled: false,
				},
			}),
		);
		expect(result?.status).toBe("manual attention");
	});

	it("defers during the active Quattro legacy shim window without reloading", async () => {
		const state = path.join(home, ".local", "state", "omarchy");
		const liveShim = path.join(state, "upgrade-to-quattro-live-omarchy");
		const share = path.join(home, ".local", "share");
		fs.mkdirSync(liveShim, { recursive: true });
		fs.mkdirSync(share, { recursive: true });
		fs.symlinkSync(liveShim, path.join(share, "omarchy"));
		fs.mkdirSync(path.join(state, "upgrade-to-quattro-hypr-defaults"));
		const hook = path.join(
			home,
			".config",
			"omarchy",
			"hooks",
			"post-boot.d",
			"cleanup-upgrade-to-quattro-live-shim",
		);
		fs.mkdirSync(path.dirname(hook), { recursive: true });
		fs.writeFileSync(hook, "#!/bin/bash\n");
		const legacy = path.join(home, ".config", "hypr", "hyprland.conf");
		fs.mkdirSync(path.dirname(legacy), { recursive: true });
		fs.writeFileSync(legacy, "# legacy config still live\n");
		const externalCalls = [];
		const inheritedEnv = {
			OMARCHY_PATH: path.join(share, "omarchy"),
			HAOSHOKU_ENV_SENTINEL: "preserved",
		};

		const result = await runAccepted({
			env: inheritedEnv,
			captureCommandImpl: async (command, options = {}) => {
				externalCalls.push({
					command,
					omarchyPath: options.env?.OMARCHY_PATH,
					sentinel: options.env?.HAOSHOKU_ENV_SENTINEL,
				});
				if (command === "omarchy version") {
					return {
						exitCode: 0,
						stdout:
							options.env?.OMARCHY_PATH === "/usr/share/omarchy"
								? "Omarchy 4.0.0\n"
								: "dev\n",
						stderr: "",
						failed: false,
					};
				}
				return { exitCode: 0, stdout: "", stderr: "", failed: false };
			},
			runCommandImpl: async (command) => {
				externalCalls.push(command);
				return true;
			},
		});

		expect(result?.steps?.find((step) => step.name === "Quattro live shim")).toEqual(
			expect.objectContaining({
				name: "Quattro live shim",
				status: "deferred",
				message: expect.stringContaining("reboot, then re-run"),
			}),
		);
		expect(result?.status).toBe("deferred");
		expect(externalCalls).toEqual([
			{
				command: "omarchy version",
				omarchyPath: "/usr/share/omarchy",
				sentinel: "preserved",
			},
		]);
	});

	it("defers immediately after the version gate without mutating any live-shim file or calling helpers", async () => {
		const state = path.join(home, ".local", "state", "omarchy");
		const liveShim = path.join(state, "upgrade-to-quattro-live-omarchy");
		const share = path.join(home, ".local", "share");
		fs.mkdirSync(liveShim, { recursive: true });
		fs.mkdirSync(share, { recursive: true });
		fs.symlinkSync(liveShim, path.join(share, "omarchy"));
		fs.mkdirSync(path.join(state, "upgrade-to-quattro-hypr-defaults"));
		const hook = path.join(
			home,
			".config",
			"omarchy",
			"hooks",
			"post-boot.d",
			"cleanup-upgrade-to-quattro-live-shim",
		);
		fs.mkdirSync(path.dirname(hook), { recursive: true });
		fs.writeFileSync(hook, "#!/bin/bash\n");
		const hypr = path.join(home, ".config", "hypr");
		fs.mkdirSync(hypr, { recursive: true });
		const legacy = path.join(hypr, "hyprland.conf");
		const orphan = path.join(hypr, "haoshoku-bindings.conf");
		const monitors = path.join(hypr, "monitors.lua");
		fs.writeFileSync(
			legacy,
			"source = ~/.config/hypr/haoshoku-bindings.conf\n",
		);
		fs.writeFileSync(orphan, "live legacy overlay\n");
		fs.writeFileSync(monitors, STOCK_MONITORS_LUA);
		const helperCalls = [];

		const result = await runAccepted({
			configureOmarchyWorkspacesImpl: async () =>
				helperCalls.push("workspaces"),
			configureHyprmoncfgImpl: async () => helperCalls.push("hyprmoncfg"),
			configureOmarchyPluginsImpl: async () => helperCalls.push("plugins"),
			runCommandImpl: async (command) => helperCalls.push(command),
		});

		expect(result.status).toBe("deferred");
		expect(result.steps).toEqual([
			{ name: "version gate", status: "clean", major: 4 },
			expect.objectContaining({
				name: "Quattro live shim",
				status: "deferred",
			}),
		]);
		expect(helperCalls).toEqual([]);
		expect(fs.readFileSync(legacy, "utf8")).toContain("haoshoku-bindings");
		expect(fs.readFileSync(orphan, "utf8")).toBe("live legacy overlay\n");
		expect(fs.readFileSync(monitors, "utf8")).toBe(STOCK_MONITORS_LUA);
	});

	it("strips a dangling monitors.conf source when the orphan is already absent", async () => {
		const legacy = path.join(home, ".config", "hypr", "hyprland.conf");
		fs.mkdirSync(path.dirname(legacy), { recursive: true });
		fs.writeFileSync(
			legacy,
			"source = ~/.config/hypr/monitors.conf\nsource = ~/.config/hypr/foreign.conf\n",
		);

		const result = await runAccepted();

		expect(fs.readFileSync(legacy, "utf8")).toBe(
			"source = ~/.config/hypr/foreign.conf\n",
		);
		expect(
			result.steps.find((step) => step.name === "legacy source cleanup"),
		).toEqual(expect.objectContaining({ status: "applied" }));
	});

	it("leaves stock monitors.lua untouched and reports manual attention when hyprmoncfg is unready", async () => {
		const monitors = path.join(home, ".config", "hypr", "monitors.lua");
		fs.mkdirSync(path.dirname(monitors), { recursive: true });
		fs.writeFileSync(monitors, STOCK_MONITORS_LUA);

		const result = await runAccepted({
			configureHyprmoncfgImpl: async () => ({
				deployed: 0,
				packageReady: false,
				serviceEnabled: false,
			}),
		});

		expect(fs.readFileSync(monitors, "utf8")).toBe(STOCK_MONITORS_LUA);
		expect(fs.existsSync(`${monitors}.bak.42`)).toBe(false);
		expect(
			result.steps.find(
				(step) => step.name === "monitors.lua ownership handoff",
			),
		).toEqual(
			expect.objectContaining({
				status: "manual attention",
				message: expect.stringContaining("not ready"),
			}),
		);
	});

	it("logs the applied handoff backup and returns recovery guidance that restores it", async () => {
		const monitors = path.join(home, ".config", "hypr", "monitors.lua");
		fs.mkdirSync(path.dirname(monitors), { recursive: true });
		fs.writeFileSync(monitors, STOCK_MONITORS_LUA);
		const messages = [];

		const result = await runAccepted({
			logImpl: {
				info: (message) => messages.push(message),
				success: (message) => messages.push(message),
				warning: (message) => messages.push(message),
				error: (message) => messages.push(message),
				dim() {},
			},
		});

		const handoff = result.steps.find(
			(step) => step.name === "monitors.lua ownership handoff",
		);
		expect(handoff).toEqual(
			expect.objectContaining({ status: "applied", backup: `${monitors}.bak.42` }),
		);
		expect(messages.join("\n")).toContain(`${monitors}.bak.42`);
		expect(result.recoveryInstruction).toContain(
			`restore ${monitors} from ${monitors}.bak.42`,
		);
	});

	it("restores a migration stock backup instead of calling a missing monitors.lua already done", async () => {
		const monitors = path.join(home, ".config", "hypr", "monitors.lua");
		fs.mkdirSync(path.dirname(monitors), { recursive: true });
		fs.writeFileSync(`${monitors}.bak.41`, STOCK_MONITORS_LUA);

		const result = await runAccepted({
			configureHyprmoncfgImpl: async () => ({
				deployed: 0,
				packageReady: false,
				serviceEnabled: false,
			}),
		});

		expect(fs.readFileSync(monitors, "utf8")).toBe(STOCK_MONITORS_LUA);
		expect(
			result.steps.find(
				(step) => step.name === "monitors.lua ownership handoff",
			),
		).toEqual(
			expect.objectContaining({
				status: "manual attention",
				restoredFrom: `${monitors}.bak.41`,
				message: expect.stringContaining("restored"),
			}),
		);
	});

	it("polls for daemon regeneration before validating without real sleep", async () => {
		const monitors = path.join(home, ".config", "hypr", "monitors.lua");
		fs.mkdirSync(path.dirname(monitors), { recursive: true });
		fs.writeFileSync(monitors, STOCK_MONITORS_LUA);
		const events = [];
		let sleeps = 0;

		const result = await runAccepted({
			sleepImpl: async (milliseconds) => {
				events.push(`sleep:${milliseconds}`);
				sleeps += 1;
				if (sleeps === 2) {
					fs.writeFileSync(
						monitors,
						"-- Generated by hyprmoncfg\nreturn {}\n",
					);
				}
			},
			captureCommandImpl: async (command) => {
				events.push(command);
				return command === "omarchy version"
					? { exitCode: 0, stdout: "Omarchy 4.0.0\n", failed: false }
					: { exitCode: 0, stdout: "\n", failed: false };
			},
			runCommandImpl: async (command) => {
				events.push(command);
				return true;
			},
		});

		expect(events).toEqual([
			"omarchy version",
			"sleep:100",
			"sleep:100",
			"hyprctl reload",
			"hyprctl configerrors",
		]);
		expect(result.status).toBe("completed");
	});

	it("reports a regeneration timeout and skips misleading Hyprland validation", async () => {
		const monitors = path.join(home, ".config", "hypr", "monitors.lua");
		fs.mkdirSync(path.dirname(monitors), { recursive: true });
		fs.writeFileSync(monitors, STOCK_MONITORS_LUA);
		const calls = [];

		const result = await runAccepted({
			sleepImpl: async (milliseconds) => calls.push(`sleep:${milliseconds}`),
			pollTimeoutMs: 300,
			pollIntervalMs: 100,
			captureCommandImpl: async (command) => {
				calls.push(command);
				return { exitCode: 0, stdout: "Omarchy 4.0.0\n", failed: false };
			},
			runCommandImpl: async (command) => calls.push(command),
		});

		expect(calls).toEqual([
			"omarchy version",
			"sleep:100",
			"sleep:100",
			"sleep:100",
		]);
		expect(
			result.steps.find((step) => step.name === "monitors.lua regeneration"),
		).toEqual(
			expect.objectContaining({
				status: "manual attention",
				restoredFrom: `${monitors}.bak.42`,
				message: expect.stringContaining("restored"),
			}),
		);
		expect(fs.readFileSync(monitors, "utf8")).toBe(STOCK_MONITORS_LUA);
		expect(
			result.steps.find((step) => step.name === "validate and hand off"),
		).toEqual(
			expect.objectContaining({
				status: "skipped",
				message: expect.stringContaining("did not regenerate"),
			}),
		);
		expect(result.status).toBe("manual attention");
	});

	it("does not accept an unmanaged monitors.lua as daemon regeneration", async () => {
		const monitors = path.join(home, ".config", "hypr", "monitors.lua");
		fs.mkdirSync(path.dirname(monitors), { recursive: true });
		fs.writeFileSync(monitors, STOCK_MONITORS_LUA);
		const calls = [];
		let recreated = false;

		const result = await runAccepted({
			pollTimeoutMs: 200,
			pollIntervalMs: 100,
			sleepImpl: async () => {
				if (!recreated) {
					recreated = true;
					fs.writeFileSync(monitors, "-- unrelated monitor config\nreturn {}\n");
				}
			},
			runCommandImpl: async (command) => calls.push(command),
			captureCommandImpl: async (command) =>
				command === "omarchy version"
					? { exitCode: 0, stdout: "Omarchy 4.0.0\n", failed: false }
					: { exitCode: 0, stdout: "", failed: false },
		});

		expect(result.status).toBe("manual attention");
		expect(
			result.steps.find((step) => step.name === "monitors.lua regeneration"),
		).toEqual(expect.objectContaining({ status: "manual attention" }));
		expect(calls).toEqual([]);
		expect(fs.readFileSync(monitors, "utf8")).toBe(STOCK_MONITORS_LUA);
	});

	it("skips validation when workspace deployment refuses or monitors.lua remains missing", async () => {
		for (const scenario of ["workspace refused", "monitors missing"]) {
			fs.rmSync(home, { recursive: true, force: true });
			fs.mkdirSync(home, { recursive: true });
			const calls = [];
			const result = await runAccepted({
				configureOmarchyWorkspacesImpl:
					scenario === "workspace refused"
						? async () => ({
								status: "refused",
								message: "hyprland.lua missing",
								sourceChanged: false,
							})
						: async () => ({}),
				configureHyprmoncfgImpl: async () => ({
					deployed: 0,
					packageReady: true,
					serviceEnabled: true,
				}),
				runCommandImpl: async (command) => calls.push(command),
			});

			expect(result.status).toBe("manual attention");
			expect(
				result.steps.find((step) => step.name === "validate and hand off"),
			).toEqual(
				expect.objectContaining({
					status: "skipped",
					message: expect.stringContaining(
						scenario === "workspace refused"
							? "workspace"
							: "monitors.lua",
					),
				}),
			);
			expect(calls).toEqual([]);
		}
	});

	it("finishes monitor regeneration before a later plugin failure can return", async () => {
		const monitors = path.join(home, ".config", "hypr", "monitors.lua");
		fs.mkdirSync(path.dirname(monitors), { recursive: true });
		fs.writeFileSync(monitors, STOCK_MONITORS_LUA);

		const result = await runAccepted({
			configureOmarchyPluginsImpl: async () => {
				throw new Error("plugin exploded after handoff");
			},
		});

		expect(result.status).toBe("failed");
		expect(fs.readFileSync(monitors, "utf8")).toStartWith(
			"-- Generated by hyprmoncfg",
		);
		expect(
			result.steps.find((step) => step.name === "monitors.lua regeneration"),
		).toEqual(expect.objectContaining({ status: "clean" }));
	});

	it("reloads then treats whitespace-only configerrors stdout as clean and returns handoff notes", async () => {
		const externalCalls = [];
		const messages = [];
		const manualAuthChecklist = [
			{ id: "weather", requirement: "authenticate in the plugin settings" },
		];
		const result = await runAccepted({
			captureCommandImpl: async (command) => {
				externalCalls.push(command);
				if (command === "omarchy version") {
					return {
						exitCode: 0,
						stdout: "Omarchy 4.1.0\n",
						stderr: "",
						failed: false,
					};
				}
				if (command === "hyprctl configerrors") {
					return { exitCode: 0, stdout: " \n", stderr: "", failed: false };
				}
				throw new Error(`unexpected ${command}`);
			},
			runCommandImpl: async (command) => {
				externalCalls.push(command);
				return true;
			},
			configureOmarchyPluginsImpl: async () => ({
				installed: [],
				enabled: [],
				alreadyReady: ["weather"],
				failed: [],
				manualAuthChecklist,
			}),
			logImpl: {
				info: (message) => messages.push(message),
				success() {},
				warning: (message) => messages.push(message),
				error: (message) => messages.push(message),
				dim() {},
			},
		});

		expect(externalCalls).toEqual([
			"omarchy version",
			"hyprctl reload",
			"hyprctl configerrors",
		]);
		expect(
			result?.steps?.find((step) => step.name === "validate and hand off")
				?.status,
		).toBe("clean");
		expect(result?.status).toBe("completed");
		expect(result?.manualAuthChecklist).toEqual(manualAuthChecklist);
		expect(result?.laptopFollowUp).toContain(
			"save a laptop hyprmoncfg profile",
		);
		expect(result?.laptopFollowUp).toContain("--hyprmoncfg-backup");
		expect(result?.recoveryInstruction).toBe(
			"remove the appended require lines from hyprland.lua, then reboot",
		);
		expect(messages.join("\n")).toContain("weather");
		expect(messages.join("\n")).toContain("--hyprmoncfg-backup");
		expect(messages.join("\n")).toContain(result?.recoveryInstruction);
	});

	it("fails validation for non-empty stdout despite exit zero or for command failure", async () => {
		for (const configErrors of [
			{
				exitCode: 0,
				stdout: "unknown config key\n",
				stderr: "",
				failed: false,
			},
			{ exitCode: 127, stdout: "", stderr: "hyprctl missing", failed: true },
		]) {
			const result = await runAccepted({
				captureCommandImpl: async (command) =>
					command === "omarchy version"
						? {
								exitCode: 0,
								stdout: "Omarchy 4.0.0\n",
								stderr: "",
								failed: false,
							}
						: configErrors,
			});
			expect(
				result?.steps?.find((step) => step.name === "validate and hand off")
					?.status,
			).toBe("failed");
			expect(result?.status).toBe("failed");
		}
	});

	it("treats configerrors output containing only a UTF-8 BOM as clean after trimming", async () => {
		const result = await runAccepted({
			captureCommandImpl: async (command) =>
				command === "omarchy version"
					? {
							exitCode: 0,
							stdout: "Omarchy 4.0.0\n",
							stderr: "",
							failed: false,
						}
					: runCommandCapture("printf '\\xEF\\xBB\\xBF'"),
		});

		const validation = result?.steps?.find(
			(step) => step.name === "validate and hand off",
		);
		expect(validation?.status).toBe("clean");
		expect(validation?.configErrors.stdout).toBe("\uFEFF");
		expect(result?.status).toBe("completed");
	});

	it("converges a real temp home on the second migration run without duplicate writes or requires", async () => {
		const hypr = path.join(home, ".config", "hypr");
		const fish = path.join(home, ".config", "fish", "config.fish");
		fs.mkdirSync(path.dirname(fish), { recursive: true });
		fs.mkdirSync(hypr, { recursive: true });
		fs.writeFileSync(
			path.join(hypr, "hyprland.conf"),
			"source = ~/.config/hypr/haoshoku-bindings.conf\nsource = ~/.config/hypr/foreign.conf\n",
		);
		fs.writeFileSync(path.join(hypr, "haoshoku-bindings.conf"), "legacy\n");
		fs.writeFileSync(
			path.join(hypr, "hyprland.lua"),
			'require("hypr.defaults")\n',
		);
		fs.writeFileSync(path.join(hypr, "monitors.lua"), STOCK_MONITORS_LUA);
		fs.writeFileSync(fish, "set theme ~/.config/omarchy/current/theme\n");
		const writes = [];
		const fsImpl = {
			...fs,
			writeFileSync(file, ...args) {
				writes.push(file);
				return fs.writeFileSync(file, ...args);
			},
		};
		let hyprmoncfgRun = 0;
		let pluginRun = 0;
		const options = {
			fsImpl,
			configureOmarchyWorkspacesImpl: configureOmarchyWorkspaces,
			configureHyprmoncfgImpl: async () => ({
				deployed: hyprmoncfgRun++ === 0 ? 1 : 0,
				packageReady: true,
				serviceEnabled: true,
			}),
			configureOmarchyPluginsImpl: async () =>
				pluginRun++ === 0
					? {
							installed: ["plugin"],
							enabled: [],
							alreadyReady: [],
							failed: [],
							manualAuthChecklist: [],
						}
					: {
							installed: [],
							enabled: [],
							alreadyReady: ["plugin"],
							failed: [],
							manualAuthChecklist: [],
						},
		};

		const first = await runAccepted(options);
		expect(
			Object.fromEntries(first.steps.map((step) => [step.name, step.status])),
		).toEqual(
			expect.objectContaining({
				"legacy source cleanup": "applied",
				"orphan cleanup": "applied",
				"live theme paths": "applied",
				"deploy reusable config": "applied",
				"monitors.lua ownership handoff": "applied",
				plugins: "applied",
				"monitors.lua regeneration": "clean",
				"validate and hand off": "clean",
			}),
		);

		writes.length = 0;
		const second = await runAccepted(options);
		expect(
			Object.fromEntries(second.steps.map((step) => [step.name, step.status])),
		).toEqual(
			expect.objectContaining({
				"legacy source cleanup": "already done",
				"orphan cleanup": "already done",
				"live theme paths": "already done",
				"deploy reusable config": "already done",
				"monitors.lua ownership handoff": "already done",
				plugins: "already done",
				"validate and hand off": "clean",
			}),
		);
		expect(writes).toEqual([]);
		const main = fs.readFileSync(path.join(hypr, "hyprland.lua"), "utf8");
		expect(main.match(/require\("hypr\.haoshoku\.bindings"\)/g)).toHaveLength(
			1,
		);
		expect(main.match(/require\("hypr\.haoshoku\.workspaces"\)/g)).toHaveLength(
			1,
		);
		expect(fs.existsSync(path.join(hypr, "hyprland.conf.bak.42.1"))).toBe(
			false,
		);
		expect(fs.existsSync(`${fish}.bak.42.1`)).toBe(false);
	});
});
