# Cursor, GTK, Qt env — keeps Ocean look-and-feel on Wayland
env = XCURSOR_THEME,Volantes
env = XCURSOR_SIZE,24
env = HYPRCURSOR_THEME,Volantes
env = HYPRCURSOR_SIZE,24
env = GTK_THEME,Juno-ocean
env = QT_QPA_PLATFORMTHEME,kvantum
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = MOZ_ENABLE_WAYLAND,1
env = NIXOS_OZONE_WL,1
env = ELECTRON_OZONE_PLATFORM_HINT,wayland
