import fs from "node:fs";
import { homedir } from "node:os";
import path from "node:path";

import { commandExists, log } from "../common/utils.js";

const PROJECT_ROOT = path.resolve(import.meta.dir, "..", "..");
const MINIMUM_VERSION = [1, 12, 0];
const SERVICE_UNIT = "hyprmoncfgd.service";
const INSTALL_HINT = "paru -S --needed --noconfirm hyprmoncfg";
const ENABLE_HINT =
	"systemctl --user daemon-reload && systemctl --user enable --now hyprmoncfgd.service";
const GENERATED_MARKER = "Generated by hyprmoncfg";

function defaultRunner(args, { env = process.env } = {}) {
	return Bun.spawnSync(args, { stdout: "pipe", stderr: "pipe", env });
}

function resolvePaths({ home = homedir(), projectRoot = PROJECT_ROOT } = {}) {
	return {
		repoProfilesDir: path.join(
			projectRoot,
			"configs",
			"hyprmoncfg",
			"profiles",
		),
		liveProfilesDir: path.join(
			home,
			".config",
			"hyprmoncfg",
			"profiles",
		),
		monitorsLua: path.join(home, ".config", "hypr", "monitors.lua"),
	};
}

function resultExitCode(result) {
	if (typeof result === "boolean") return result ? 0 : 1;
	if (typeof result === "number") return result;
	return result?.exitCode ?? 1;
}

function resultOutput(result) {
	const output = result?.stdout;
	if (typeof output === "string") return output;
	if (output === undefined || output === null) return "";
	return output.toString();
}

function parseVersion(result) {
	if (resultExitCode(result) !== 0) return null;
	const match = resultOutput(result).match(/v?(\d+)\.(\d+)\.(\d+)/);
	return match ? match.slice(1, 4).map(Number) : null;
}

function versionAtLeast(actual, minimum = MINIMUM_VERSION) {
	if (!actual) return false;
	for (let index = 0; index < minimum.length; index += 1) {
		if (actual[index] > minimum[index]) return true;
		if (actual[index] < minimum[index]) return false;
	}
	return true;
}

function jsonFiles(fsImpl, directory) {
	return fsImpl
		.readdirSync(directory, { withFileTypes: true })
		.filter((entry) => entry.isFile() && entry.name.endsWith(".json"))
		.map((entry) => entry.name)
		.sort();
}

function availablePath(fsImpl, basePath) {
	let candidate = basePath;
	let suffix = 0;
	while (fsImpl.existsSync(candidate)) {
		suffix += 1;
		candidate = `${basePath}.${suffix}`;
	}
	return candidate;
}

function writeAtomically(fsImpl, destination, contents, timestamp) {
	const temporary = availablePath(
		fsImpl,
		`${destination}.tmp.${timestamp}`,
	);
	try {
		fsImpl.writeFileSync(temporary, contents);
		fsImpl.renameSync(temporary, destination);
	} finally {
		if (fsImpl.existsSync(temporary)) {
			fsImpl.rmSync(temporary, { force: true });
		}
	}
}

function replaceWithBackup({ fsImpl, source, destination, now }) {
	const desired = fsImpl.readFileSync(source);
	fsImpl.mkdirSync(path.dirname(destination), { recursive: true });
	if (
		fsImpl.existsSync(destination) &&
		fsImpl.readFileSync(destination).equals(desired)
	) {
		return { changed: false, backup: null };
	}

	const timestamp = now();
	let backup = null;
	if (fsImpl.existsSync(destination)) {
		backup = availablePath(fsImpl, `${destination}.bak.${timestamp}`);
		writeAtomically(
			fsImpl,
			backup,
			fsImpl.readFileSync(destination),
			timestamp,
		);
		log.info(`Backed up existing ${path.basename(destination)} to ${backup}`);
	}

	writeAtomically(fsImpl, destination, desired, timestamp);
	return { changed: true, backup };
}

function warnAboutUserOwnedMonitorsLua(fsImpl, monitorsLua) {
	if (!fsImpl.existsSync(monitorsLua)) return;
	const firstLine = fsImpl.readFileSync(monitorsLua, "utf8").split(/\r?\n/, 1)[0];
	if (firstLine.includes(GENERATED_MARKER)) return;
	log.warning(
		`Existing user-owned monitor file at ${monitorsLua} is not marked "${GENERATED_MARKER}"; the hyprmoncfg daemon will refuse to replace it. Haoshoku left it untouched.`,
	);
}

async function commandAvailable(commandExistsImpl, command) {
	try {
		return Boolean(await commandExistsImpl(command));
	} catch {
		return false;
	}
}

async function runSafely(runCommandImpl, args, env) {
	try {
		return await runCommandImpl(args, { env });
	} catch {
		return { exitCode: 127, stdout: "" };
	}
}

async function probeHyprmoncfgVersion(runCommandImpl, env) {
	return parseVersion(
		await runSafely(runCommandImpl, ["hyprmoncfg", "--version"], env),
	);
}

async function ensureHyprmoncfg({
	commandExistsImpl,
	runCommandImpl,
	env,
}) {
	if (await commandAvailable(commandExistsImpl, "hyprmoncfg")) {
		const installedVersion = await probeHyprmoncfgVersion(runCommandImpl, env);
		if (versionAtLeast(installedVersion)) return true;
	}

	let aurHelper = null;
	for (const candidate of ["paru", "yay"]) {
		if (await commandAvailable(commandExistsImpl, candidate)) {
			aurHelper = candidate;
			break;
		}
	}
	if (!aurHelper) {
		log.warning(
			`No AUR helper (paru or yay) is available; install hyprmoncfg >= 1.12.0 manually:\n  ${INSTALL_HINT}`,
		);
		return false;
	}

	const installed = await runSafely(
		runCommandImpl,
		[aurHelper, "-S", "--needed", "--noconfirm", "hyprmoncfg"],
		env,
	);
	if (resultExitCode(installed) !== 0) {
		log.warning(
			`Could not install hyprmoncfg automatically. Run manually:\n  ${aurHelper} -S --needed --noconfirm hyprmoncfg`,
		);
		return false;
	}

	const installedVersion = await probeHyprmoncfgVersion(runCommandImpl, env);
	if (!versionAtLeast(installedVersion)) {
		log.warning(
			"hyprmoncfg installation finished, but version >= 1.12.0 could not be confirmed.",
		);
		return false;
	}
	log.success("hyprmoncfg >= 1.12.0 is installed.");
	return true;
}

async function enableService(runCommandImpl, env) {
	const probe = await runSafely(
		runCommandImpl,
		["systemctl", "--user", "--version"],
		env,
	);
	if (resultExitCode(probe) !== 0) {
		log.warning(
			`systemctl --user unavailable — skipping service enable. Run manually:\n  ${ENABLE_HINT}`,
		);
		return false;
	}

	const reload = await runSafely(
		runCommandImpl,
		["systemctl", "--user", "daemon-reload"],
		env,
	);
	const enabled = await runSafely(
		runCommandImpl,
		["systemctl", "--user", "enable", "--now", SERVICE_UNIT],
		env,
	);
	if (resultExitCode(reload) === 0 && resultExitCode(enabled) === 0) {
		log.success(`Enabled ${SERVICE_UNIT} (systemctl --user)`);
		return true;
	}

	log.warning(
		`Could not enable ${SERVICE_UNIT} automatically. Run manually:\n  ${ENABLE_HINT}`,
	);
	return false;
}

/** Deploy repository profile JSON, ensure hyprmoncfg, and start its user daemon. */
export async function syncHyprmoncfg({
	home = homedir(),
	projectRoot = PROJECT_ROOT,
	fsImpl = fs,
	now = Date.now,
	runCommandImpl = defaultRunner,
	commandExistsImpl = commandExists,
	env = process.env,
	enable = true,
} = {}) {
	const { repoProfilesDir, liveProfilesDir, monitorsLua } = resolvePaths({
		home,
		projectRoot,
	});
	warnAboutUserOwnedMonitorsLua(fsImpl, monitorsLua);

	let deployed = 0;
	if (!fsImpl.existsSync(repoProfilesDir)) {
		log.warning(
			`No hyprmoncfg profile source directory found at ${repoProfilesDir} — skipping deploy.`,
		);
	} else {
		fsImpl.mkdirSync(liveProfilesDir, { recursive: true });
		for (const filename of jsonFiles(fsImpl, repoProfilesDir)) {
			const result = replaceWithBackup({
				fsImpl,
				source: path.join(repoProfilesDir, filename),
				destination: path.join(liveProfilesDir, filename),
				now,
			});
			if (result.changed) deployed += 1;
		}
	}

	const packageReady = await ensureHyprmoncfg({
		commandExistsImpl,
		runCommandImpl,
		env,
	});
	const serviceEnabled = enable
		? await enableService(runCommandImpl, env)
		: false;
	return { deployed, packageReady, serviceEnabled };
}

/** Back up canonical live JSON profiles; generated conf/lua sidecars are ignored. */
export async function backupHyprmoncfg({
	home = homedir(),
	projectRoot = PROJECT_ROOT,
	fsImpl = fs,
	now = Date.now,
} = {}) {
	const { repoProfilesDir, liveProfilesDir } = resolvePaths({
		home,
		projectRoot,
	});
	if (!fsImpl.existsSync(liveProfilesDir)) {
		log.warning(
			`No live hyprmoncfg profile directory found at ${liveProfilesDir} — nothing to back up.`,
		);
		return { backedUp: 0 };
	}

	fsImpl.mkdirSync(repoProfilesDir, { recursive: true });
	let backedUp = 0;
	for (const filename of jsonFiles(fsImpl, liveProfilesDir)) {
		const result = replaceWithBackup({
			fsImpl,
			source: path.join(liveProfilesDir, filename),
			destination: path.join(repoProfilesDir, filename),
			now,
		});
		if (result.changed) backedUp += 1;
	}
	return { backedUp };
}

/** Alias used by future OS/CLI wiring. */
export async function configureHyprmoncfg(opts = {}) {
	return await syncHyprmoncfg(opts);
}
