import fs from "node:fs";
import path from "node:path";
import { log, promptUser, runCommand } from "../common/utils.js";

// ---------------------------------------------------------------------------
// Executor self-host provisioning, Tailscale-only.
//
// Executor holds long-lived OAuth tokens for every connected account (Gmail,
// Notion, Linear, ...), so this path deliberately publishes NOTHING to the
// public internet: the container binds loopback and `tailscale serve`
// terminates TLS at the node's MagicDNS name. That is also a hard requirement
// rather than a preference — Tailscale serve only accepts `http://127.0.0.1`
// as a proxy target.
//
// EXECUTOR_WEB_BASE_URL must equal the origin the browser actually loads or
// Better Auth rejects every login with "Invalid origin", so it is derived from
// the live `tailscale status` MagicDNS name rather than typed by hand.
// ---------------------------------------------------------------------------

const EXECUTOR_IMAGE = "ghcr.io/rhyssullivan/executor-selfhost:latest";
const EXECUTOR_PORT = 4788;
const DEFAULT_DATA_DIR = "/srv/executor";
const DEFAULT_HTTPS_PORT = 443;
const FALLBACK_HTTPS_PORT = 8443;
const COMPOSE_FILENAME = "docker-compose.yml";

/**
 * Pull the local node's MagicDNS name out of `tailscale status --json`.
 * `Self.DNSName` arrives FQDN-style with a trailing dot, which must not survive
 * into an origin. Returns null for anything unparseable so callers can report a
 * setup gap instead of building a bad URL.
 */
export function parseTailnetDnsName(statusOutput) {
	if (typeof statusOutput !== "string" || statusOutput.trim() === "") {
		return null;
	}
	let parsed;
	try {
		parsed = JSON.parse(statusOutput);
	} catch {
		return null;
	}
	if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
		return null;
	}
	const dnsName = parsed.Self?.DNSName;
	if (typeof dnsName !== "string") return null;
	const trimmed = dnsName.trim().replace(/\.+$/, "");
	return trimmed === "" ? null : trimmed;
}

/**
 * Build the canonical origin Executor is configured for. No port, because
 * `tailscale serve` terminates on 443; no trailing slash, because Better Auth
 * compares the Origin header literally.
 */
export function executorBaseUrlFromTailnetName(
	name,
	httpsPort = DEFAULT_HTTPS_PORT,
) {
	if (typeof name !== "string") {
		throw new TypeError("Tailnet DNS name must be a string.");
	}
	const trimmed = name.trim().replace(/\.+$/, "");
	if (trimmed === "") {
		throw new Error("Tailnet DNS name is empty.");
	}
	if (/:\/\//.test(trimmed)) {
		throw new Error(
			`Expected a bare tailnet DNS name, got a URL: ${trimmed}. Pass the MagicDNS name only.`,
		);
	}
	return httpsPort === DEFAULT_HTTPS_PORT
		? `https://${trimmed}`
		: `https://${trimmed}:${httpsPort}`;
}

/**
 * Render the compose file. `EXECUTOR_SECRET_KEY` and `BETTER_AUTH_SECRET` are
 * intentionally absent: Executor generates and persists both under /data, and
 * pinning them here would put the key that encrypts every stored OAuth token
 * into a config file.
 */
export function buildExecutorComposeFile({ baseUrl, dataDir } = {}) {
	if (typeof baseUrl !== "string" || baseUrl.trim() === "") {
		throw new Error("buildExecutorComposeFile requires a baseUrl.");
	}
	if (typeof dataDir !== "string" || dataDir.trim() === "") {
		throw new Error("buildExecutorComposeFile requires a dataDir.");
	}
	return `# Managed by Haoshoku — regenerated by \`haoshoku --server-executor\`.
# Loopback-only by design: \`tailscale serve\` fronts this with TLS and is the
# ONLY supported way in. Do not publish this port on a public interface.
services:
  executor:
    image: ${EXECUTOR_IMAGE}
    container_name: executor-selfhost
    restart: unless-stopped
    ports:
      - "127.0.0.1:${EXECUTOR_PORT}:${EXECUTOR_PORT}"
    volumes:
      - ${dataDir.trim()}:/data
    environment:
      - EXECUTOR_WEB_BASE_URL=${baseUrl.trim()}
`;
}

/** The command that puts Executor on the tailnet over HTTPS. */
export function tailscaleServeCommand(port, httpsPort = DEFAULT_HTTPS_PORT) {
	if (!Number.isInteger(port) || port < 1 || port > 65535) {
		throw new Error(`Invalid port for tailscale serve: ${port}`);
	}
	if (!Number.isInteger(httpsPort) || httpsPort < 1 || httpsPort > 65535) {
		throw new Error(`Invalid HTTPS port for tailscale serve: ${httpsPort}`);
	}
	return `sudo tailscale serve --bg --https=${httpsPort} http://127.0.0.1:${port}`;
}

/** Read the live MagicDNS name, or null when Tailscale is absent or logged out. */
export function readTailnetDnsName({ spawnSyncImpl = Bun.spawnSync } = {}) {
	const result = spawnSyncImpl(["tailscale", "status", "--json"], {
		stderr: "ignore",
		stdout: "pipe",
	});
	if (!result || result.exitCode !== 0) return null;
	return parseTailnetDnsName(new TextDecoder().decode(result.stdout));
}

export async function configureExecutor({
	dataDir = DEFAULT_DATA_DIR,
	logger = log,
	readDnsNameImpl = readTailnetDnsName,
	runCommandImpl = runCommand,
	promptUserImpl = promptUser,
	chooseHttpsPortImpl = chooseHttpsPort,
	waitForExecutorImpl = waitForExecutor,
} = {}) {
	const dnsName = readDnsNameImpl();
	if (!dnsName) {
		logger.error(
			"Tailscale is not available or this node is logged out — cannot derive EXECUTOR_WEB_BASE_URL. Run `sudo tailscale up`, then re-run this step.",
		);
		return false;
	}

	let httpsPort;
	try {
		httpsPort = chooseHttpsPortImpl();
	} catch (err) {
		logger.error(err?.message ?? String(err));
		return false;
	}
	if (httpsPort !== DEFAULT_HTTPS_PORT) {
		logger.warning(
			`Port ${DEFAULT_HTTPS_PORT} is already in use on this host, so Executor will be served on ${httpsPort} instead.`,
		);
	}

	const baseUrl = executorBaseUrlFromTailnetName(dnsName, httpsPort);
	logger.info(`Executor will be served at ${baseUrl} (tailnet only).`);

	if (!(await promptUserImpl(`Install Executor at ${baseUrl}?`, true))) {
		logger.info("Skipping Executor setup.");
		return false;
	}

	if (!(await runCommandImpl(`sudo mkdir -p ${dataDir}`))) {
		logger.error(`Could not create the Executor data directory at ${dataDir}.`);
		return false;
	}

	const composePath = path.join(dataDir, COMPOSE_FILENAME);
	const compose = buildExecutorComposeFile({ baseUrl, dataDir });
	const stagedPath = path.join(
		fs.mkdtempSync(path.join("/tmp", "haoshoku-executor-")),
		COMPOSE_FILENAME,
	);
	fs.writeFileSync(stagedPath, compose);
	if (!(await runCommandImpl(`sudo cp ${stagedPath} ${composePath}`))) {
		logger.error(`Could not write the compose file to ${composePath}.`);
		return false;
	}

	if (!(await runCommandImpl(`sudo docker compose -f ${composePath} up -d`))) {
		logger.error("Executor container failed to start.");
		return false;
	}

	if (
		!(await runCommandImpl(tailscaleServeCommand(EXECUTOR_PORT, httpsPort)))
	) {
		logger.error(
			"Executor is running but `tailscale serve` failed — it is currently reachable only from the host itself.",
		);
		return false;
	}

	if (!(await waitForExecutorImpl(baseUrl))) {
		logger.error(
			`Executor's container is running but ${baseUrl} never answered. Check for another listener on port ${httpsPort} (\`ss -tlnp | grep :${httpsPort}\`) — a process bound to 0.0.0.0 also covers the Tailscale address and will take the port from \`tailscale serve\`.`,
		);
		return false;
	}

	logger.success(`Executor is up at ${baseUrl}`);
	logger.info(
		`Next: open ${baseUrl} from a device on this tailnet to create the owner account and connect your accounts. Point agents at ${baseUrl}/mcp.`,
	);
	return true;
}

/**
 * Pick the HTTPS port `tailscale serve` should terminate on.
 *
 * Found the hard way on the first real VPS run: an existing nginx bound to
 * 0.0.0.0:443 also covers the Tailscale IP, so serve silently loses 443 and the
 * MagicDNS name answers with that other vhost's certificate. Anything already
 * holding 443 sends us to 8443 rather than producing a broken endpoint.
 */
export function chooseHttpsPort({ portInUse = isPortInUse } = {}) {
	if (!portInUse(DEFAULT_HTTPS_PORT)) return DEFAULT_HTTPS_PORT;
	if (!portInUse(FALLBACK_HTTPS_PORT)) return FALLBACK_HTTPS_PORT;
	throw new Error(
		`Both ${DEFAULT_HTTPS_PORT} and ${FALLBACK_HTTPS_PORT} are already in use — free one or configure Executor's HTTPS port explicitly.`,
	);
}

/** True when any process already listens on `port`. */
export function isPortInUse(port, { spawnSyncImpl = Bun.spawnSync } = {}) {
	const result = spawnSyncImpl(["ss", "-tln"], {
		stderr: "ignore",
		stdout: "pipe",
	});
	if (!result || result.exitCode !== 0) return false;
	const output = new TextDecoder().decode(result.stdout);
	return new RegExp(`:${port}\\s`, "m").test(output);
}

/**
 * Prove the endpoint actually answers. A command exit code is not evidence:
 * the first real run reported success while TLS was serving a foreign
 * certificate. A 4xx counts — Executor's own auth wall is a working Executor.
 */
export async function isExecutorReachable(baseUrl, { fetchImpl = fetch } = {}) {
	try {
		const response = await fetchImpl(baseUrl, { redirect: "manual" });
		return response.status >= 200 && response.status < 500;
	} catch {
		return false;
	}
}

/**
 * Poll until Executor answers or the budget runs out. The container reports
 * `health: starting` for a few seconds after `compose up`, and a single probe
 * in that window fails a deploy that is actually fine.
 */
export async function waitForExecutor(
	baseUrl,
	{
		attempts = 20,
		delayMs = 1500,
		isReachableImpl = isExecutorReachable,
		sleepImpl = (ms) => new Promise((resolve) => setTimeout(resolve, ms)),
	} = {},
) {
	for (let attempt = 1; attempt <= attempts; attempt += 1) {
		if (await isReachableImpl(baseUrl)) return true;
		if (attempt < attempts) await sleepImpl(delayMs);
	}
	return false;
}
