import fs from "node:fs";
import { homedir } from "node:os";
import path from "node:path";

import { log, runCommand, runCommandCapture } from "../common/utils.js";
import { configureHyprmoncfg } from "./configure_hyprmoncfg.js";
import { configureOmarchyPlugins } from "./configure_omarchy_plugins.js";
import { configureOmarchyWorkspaces } from "./configure_omarchy_workspaces.js";

function availablePath(fsImpl, base) {
	let candidate = base;
	let collision = 1;
	while (fsImpl.existsSync(candidate)) {
		candidate = `${base}.${collision}`;
		collision += 1;
	}
	return candidate;
}

function writeAtomically(fsImpl, destination, contents, timestamp, mode) {
	const temporary = availablePath(
		fsImpl,
		path.join(
			path.dirname(destination),
			`.${path.basename(destination)}.tmp.${timestamp}`,
		),
	);
	try {
		fsImpl.writeFileSync(
			temporary,
			contents,
			mode === undefined ? undefined : { mode },
		);
		if (mode !== undefined) fsImpl.chmodSync(temporary, mode);
		fsImpl.renameSync(temporary, destination);
	} finally {
		if (fsImpl.existsSync(temporary)) fsImpl.rmSync(temporary, { force: true });
	}
}

function backupFile(fsImpl, source, now) {
	const timestamp = now();
	const backup = availablePath(fsImpl, `${source}.bak.${timestamp}`);
	const mode = fsImpl.statSync(source).mode & 0o777;
	writeAtomically(fsImpl, backup, fsImpl.readFileSync(source), timestamp, mode);
	return { backup, timestamp, mode };
}

function isHaoshokuSource(line) {
	const match = line.match(
		/^[ \t]*source[ \t]*=[ \t]*([^#\r\n]+?)[ \t]*(?:#.*)?$/,
	);
	if (!match) return false;
	const value = match[1].trim().replace(/^(?:"(.*)"|'(.*)')$/, "$1$2");
	return /^haoshoku-[^/\\\s]+\.conf$/.test(path.basename(value));
}

function withoutHaoshokuSources(content) {
	return (content.match(/[^\r\n]*(?:\r\n|\r|\n|$)/g) ?? [])
		.filter(
			(line) => line && !isHaoshokuSource(line.replace(/\r\n|\r|\n$/, "")),
		)
		.join("");
}

function cleanLegacySources({ home, fsImpl, now }) {
	const legacy = path.join(home, ".config", "hypr", "hyprland.conf");
	if (!fsImpl.existsSync(legacy)) {
		return { name: "legacy source cleanup", status: "already done" };
	}
	const original = fsImpl.readFileSync(legacy, "utf8");
	const cleaned = withoutHaoshokuSources(original);
	if (cleaned === original) {
		return { name: "legacy source cleanup", status: "already done" };
	}
	const { backup, timestamp, mode } = backupFile(fsImpl, legacy, now);
	writeAtomically(fsImpl, legacy, cleaned, timestamp, mode);
	return { name: "legacy source cleanup", status: "applied", backup };
}

const HYPRMONCFG_MARKERS = new Set([
	"# Generated by hyprmoncfg",
	"-- Generated by hyprmoncfg",
]);

function isHyprmoncfgOwned(fsImpl, file) {
	const content = fsImpl.readFileSync(file, "utf8").replace(/^\uFEFF/, "");
	const firstLine = content.split(/\r\n|\r|\n/, 1)[0];
	return HYPRMONCFG_MARKERS.has(firstLine);
}

function removeOrphans({ home, fsImpl, now }) {
	const hypr = path.join(home, ".config", "hypr");
	const files = [
		path.join(hypr, "haoshoku-bindings.conf"),
		path.join(hypr, "haoshoku-workspaces.conf"),
		path.join(hypr, "monitors.conf"),
	].map((file) => {
		if (!fsImpl.existsSync(file)) return { path: file, status: "already done" };
		if (
			path.basename(file) === "monitors.conf" &&
			isHyprmoncfgOwned(fsImpl, file)
		) {
			return {
				path: file,
				status: "already done",
				reason: "hyprmoncfg-owned",
			};
		}
		const { backup } = backupFile(fsImpl, file, now);
		fsImpl.unlinkSync(file);
		return { path: file, status: "applied", backup };
	});
	return {
		name: "orphan cleanup",
		status: files.some((file) => file.status === "applied")
			? "applied"
			: "already done",
		files,
	};
}

const LEGACY_THEME_PATH = "~/.config/omarchy/current";
const QUATTRO_THEME_PATH = "~/.local/state/omarchy/current";
const STOCK_MONITORS_LUA = `-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
-- List current monitors and supported resolutions with: hyprctl monitors all

local omarchy_gdk_scale = 2
local omarchy_monitor_scale = "auto"

hl.env("GDK_SCALE", tostring(omarchy_gdk_scale))
hl.monitor({ output = "", mode = "preferred", position = "auto", scale = omarchy_monitor_scale })

-- Configure a specific monitor.
-- hl.monitor({ output = "DP-2", mode = "2560x1440@144", position = "0x0", scale = 1 })

-- Portrait/rotated secondary monitor (transform: 1 = 90°, 3 = 270°).
-- hl.monitor({ output = "DP-2", mode = "preferred", position = "auto", scale = 1, transform = 1 })
`;

function rewriteLiveThemePaths({ home, fsImpl, now }) {
	const files = [
		path.join(home, ".config", "fish", "config.fish"),
		path.join(home, ".config", "kitty", "haki.session"),
		path.join(home, ".config", "kitty", "agents.session"),
	].map((file) => {
		if (!fsImpl.existsSync(file)) return { path: file, status: "already done" };
		const original = fsImpl.readFileSync(file, "utf8");
		const desired = original.replaceAll(LEGACY_THEME_PATH, QUATTRO_THEME_PATH);
		if (desired === original) return { path: file, status: "already done" };
		const { backup, timestamp, mode } = backupFile(fsImpl, file, now);
		writeAtomically(fsImpl, file, desired, timestamp, mode);
		return { path: file, status: "applied", backup };
	});
	return {
		name: "live theme paths",
		status: files.some((file) => file.status === "applied")
			? "applied"
			: "already done",
		files,
	};
}

function identicalBackup(fsImpl, file, contents) {
	const directory = path.dirname(file);
	if (!fsImpl.existsSync(directory)) return null;
	const prefix = `${path.basename(file)}.bak.`;
	for (const candidate of fsImpl.readdirSync(directory)) {
		if (!candidate.startsWith(prefix)) continue;
		const backup = path.join(directory, candidate);
		if (fsImpl.readFileSync(backup).equals(contents)) return backup;
	}
	return null;
}

function handoffMonitorsLua({ home, fsImpl, now, logImpl }) {
	const monitors = path.join(home, ".config", "hypr", "monitors.lua");
	if (!fsImpl.existsSync(monitors) || isHyprmoncfgOwned(fsImpl, monitors)) {
		return {
			name: "monitors.lua ownership handoff",
			status: "already done",
		};
	}
	const contents = fsImpl.readFileSync(monitors);
	if (contents.equals(Buffer.from(STOCK_MONITORS_LUA))) {
		const { backup } = backupFile(fsImpl, monitors, now);
		fsImpl.unlinkSync(monitors);
		return {
			name: "monitors.lua ownership handoff",
			status: "applied",
			backup,
		};
	}

	let backup = identicalBackup(fsImpl, monitors, contents);
	if (!backup) backup = backupFile(fsImpl, monitors, now).backup;
	const message = `manual attention: customized ${monitors} remains in place; hyprmoncfg will refuse to manage monitors until it is reconciled or removed.`;
	logImpl.warning(message);
	return {
		name: "monitors.lua ownership handoff",
		status: "manual attention",
		backup,
		message,
	};
}

function quattroShimIsActive(home, fsImpl) {
	const state = path.join(home, ".local", "state", "omarchy");
	const shareLink = path.join(home, ".local", "share", "omarchy");
	const linkState = fsImpl.lstatSync(shareLink, { throwIfNoEntry: false });
	if (!linkState?.isSymbolicLink()) return false;
	const target = path.resolve(
		path.dirname(shareLink),
		fsImpl.readlinkSync(shareLink),
	);
	return (
		target === path.join(state, "upgrade-to-quattro-live-omarchy") &&
		fsImpl.existsSync(path.join(state, "upgrade-to-quattro-hypr-defaults")) &&
		fsImpl.existsSync(
			path.join(
				home,
				".config",
				"omarchy",
				"hooks",
				"post-boot.d",
				"cleanup-upgrade-to-quattro-live-shim",
			),
		) &&
		fsImpl.existsSync(path.join(home, ".config", "hypr", "hyprland.conf"))
	);
}

function omarchyMajor(result) {
	if (result?.exitCode !== 0) return null;
	const match = result.stdout?.match(/\bv?(\d+)(?:\.\d+){1,2}\b/);
	return match ? Number(match[1]) : null;
}

export async function migrateOmarchy3To4({
	home = homedir(),
	fsImpl = fs,
	now = Date.now,
	env = process.env,
	captureCommandImpl = runCommandCapture,
	runCommandImpl = runCommand,
	logImpl = log,
	configureOmarchyWorkspacesImpl = configureOmarchyWorkspaces,
	configureHyprmoncfgImpl = configureHyprmoncfg,
	configureOmarchyPluginsImpl = configureOmarchyPlugins,
} = {}) {
	const version = await captureCommandImpl("omarchy version", {
		env: { ...env, OMARCHY_PATH: "/usr/share/omarchy" },
	});
	const major = omarchyMajor(version);
	if (major === null || major < 4) {
		const message =
			"Migration refused: Omarchy 4 or newer must be installed and its version must be detectable.";
		logImpl.warning(message);
		return {
			status: "refused",
			steps: [{ name: "version gate", status: "refused", message }],
		};
	}

	const steps = [
		{ name: "version gate", status: "clean", major },
		cleanLegacySources({ home, fsImpl, now }),
		removeOrphans({ home, fsImpl, now }),
		rewriteLiveThemePaths({ home, fsImpl, now }),
		handoffMonitorsLua({ home, fsImpl, now, logImpl }),
	];
	const laptopFollowUp =
		"On a laptop, save a laptop hyprmoncfg profile and run --hyprmoncfg-backup.";
	const recoveryInstruction =
		"remove the appended require lines from hyprland.lua, then reboot";
	logImpl.info(recoveryInstruction);

	let workspaces;
	let hyprmoncfg;
	let deployFailure = null;
	try {
		workspaces =
			(await configureOmarchyWorkspacesImpl({ home, fsImpl, now })) ?? {};
	} catch (error) {
		const message = `Workspace deployment failed: ${error instanceof Error ? error.message : String(error)}`;
		workspaces = { status: "failed", message };
		hyprmoncfg = {
			status: "skipped",
			message: "Skipped because workspace deployment failed.",
		};
		deployFailure = message;
	}
	if (!deployFailure) {
		try {
			hyprmoncfg = (await configureHyprmoncfgImpl({ home, fsImpl, now })) ?? {};
		} catch (error) {
			const message = `hyprmoncfg deployment failed: ${error instanceof Error ? error.message : String(error)}`;
			hyprmoncfg = { status: "failed", message };
			deployFailure = message;
		}
	}
	if (deployFailure) {
		logImpl.error(deployFailure);
		steps.push({
			name: "deploy reusable config",
			status: "failed",
			workspaces,
			hyprmoncfg,
			message: deployFailure,
		});
		steps.push({
			name: "plugins",
			status: "skipped",
			message: "Skipped because reusable configuration deployment failed.",
		});
		steps.push({
			name: "validate and hand off",
			status: "skipped",
			message:
				"Skipped because reusable configuration deployment failed; Hyprland was not reloaded.",
		});
		return {
			status: "failed",
			steps,
			manualAuthChecklist: [],
			laptopFollowUp,
			recoveryInstruction,
		};
	}
	const unreadyHyprmoncfgParts = [];
	if (hyprmoncfg.packageReady !== true) unreadyHyprmoncfgParts.push("package");
	if (hyprmoncfg.serviceEnabled !== true)
		unreadyHyprmoncfgParts.push("service");
	const deployStep = {
		name: "deploy reusable config",
		status:
			unreadyHyprmoncfgParts.length > 0
				? "manual attention"
				: Object.values(workspaces).some((value) => value === true) ||
						Number(hyprmoncfg.deployed) > 0
					? "applied"
					: "already done",
		workspaces,
		hyprmoncfg,
	};
	if (unreadyHyprmoncfgParts.length > 0) {
		deployStep.message = `hyprmoncfg ${unreadyHyprmoncfgParts.join(" and ")} ${unreadyHyprmoncfgParts.length === 1 ? "is" : "are"} not ready; complete installation/service setup and re-run.`;
		logImpl.warning(deployStep.message);
	}
	steps.push(deployStep);

	let plugins;
	try {
		plugins = (await configureOmarchyPluginsImpl({ logImpl })) ?? {};
	} catch (error) {
		const message = `Plugin deployment failed: ${error instanceof Error ? error.message : String(error)}`;
		logImpl.error(message);
		steps.push({ name: "plugins", status: "failed", message });
		steps.push({
			name: "validate and hand off",
			status: "skipped",
			message:
				"Skipped because plugin deployment failed; Hyprland was not reloaded.",
		});
		return {
			status: "failed",
			steps,
			manualAuthChecklist: [],
			laptopFollowUp,
			recoveryInstruction,
		};
	}
	steps.push({
		name: "plugins",
		status:
			plugins.failed?.length > 0
				? "manual attention"
				: plugins.installed?.length > 0 || plugins.enabled?.length > 0
					? "applied"
					: "already done",
		result: plugins,
	});

	let validation;
	if (quattroShimIsActive(home, fsImpl)) {
		validation = {
			name: "validate and hand off",
			status: "deferred",
			message:
				"The Quattro live compatibility shim is still active; reboot, then re-run this migration.",
		};
		logImpl.warning(validation.message);
	} else {
		const reloaded = await runCommandImpl("hyprctl reload", { check: false });
		const configErrors = await captureCommandImpl("hyprctl configerrors");
		const clean =
			reloaded === true &&
			configErrors?.exitCode === 0 &&
			configErrors.failed === false &&
			configErrors.stdout === "";
		validation = {
			name: "validate and hand off",
			status: clean ? "clean" : "failed",
			reloaded,
			configErrors,
		};
		if (clean) logImpl.success("Hyprland reloaded with no config errors.");
		else
			logImpl.error(
				"Hyprland validation failed; inspect the captured configerrors output before continuing.",
			);
	}
	steps.push(validation);

	const manualAuthChecklist = plugins.manualAuthChecklist ?? [];
	if (manualAuthChecklist.length > 0) {
		logImpl.info("Omarchy plugin manual-auth checklist:");
		for (const item of manualAuthChecklist) {
			logImpl.info(`  - ${item.id}: ${item.requirement}`);
		}
	}
	logImpl.info(laptopFollowUp);

	const status =
		validation.status === "deferred"
			? "deferred"
			: validation.status === "failed"
				? "failed"
				: steps.some((step) => step.status === "manual attention")
					? "manual attention"
					: "completed";
	return {
		status,
		steps,
		manualAuthChecklist,
		laptopFollowUp,
		recoveryInstruction,
	};
}
