import fs from "node:fs";
import { homedir } from "node:os";
import path from "node:path";

import { checkOmarchyV4 } from "../common/omarchy_version.js";
import { log, runCommand, runCommandCapture } from "../common/utils.js";
import { configureHyprmoncfg } from "./configure_hyprmoncfg.js";
import { configureOmarchyPlugins } from "./configure_omarchy_plugins.js";
import { configureOmarchyWorkspaces } from "./configure_omarchy_workspaces.js";

function availablePath(fsImpl, base) {
	let candidate = base;
	let collision = 1;
	while (fsImpl.existsSync(candidate)) {
		candidate = `${base}.${collision}`;
		collision += 1;
	}
	return candidate;
}

function writeAtomically(fsImpl, destination, contents, timestamp, mode) {
	const temporary = availablePath(
		fsImpl,
		path.join(
			path.dirname(destination),
			`.${path.basename(destination)}.tmp.${timestamp}`,
		),
	);
	try {
		fsImpl.writeFileSync(
			temporary,
			contents,
			mode === undefined ? undefined : { mode },
		);
		if (mode !== undefined) fsImpl.chmodSync(temporary, mode);
		fsImpl.renameSync(temporary, destination);
	} finally {
		if (fsImpl.existsSync(temporary)) fsImpl.rmSync(temporary, { force: true });
	}
}

function backupFile(fsImpl, source, now) {
	const timestamp = now();
	const backup = availablePath(fsImpl, `${source}.bak.${timestamp}`);
	const mode = fsImpl.statSync(source).mode & 0o777;
	writeAtomically(fsImpl, backup, fsImpl.readFileSync(source), timestamp, mode);
	return { backup, timestamp, mode };
}

function sourcePath(line) {
	const match = line.match(
		/^[ \t]*source[ \t]*=[ \t]*([^#\r\n]+?)[ \t]*(?:#.*)?$/,
	);
	if (!match) return null;
	const value = match[1].trim().replace(/^(?:"(.*)"|'(.*)')$/, "$1$2");
	return value;
}

function isRetiredSource(line, { stripMonitorsConf }) {
	const value = sourcePath(line);
	if (!value) return false;
	const basename = path.basename(value);
	return (
		/^haoshoku-[^/\\\s]+\.conf$/.test(basename) ||
		(stripMonitorsConf && basename === "monitors.conf")
	);
}

function withoutRetiredSources(content, options) {
	return (content.match(/[^\r\n]*(?:\r\n|\r|\n|$)/g) ?? [])
		.filter(
			(line) =>
				line &&
				!isRetiredSource(line.replace(/\r\n|\r|\n$/, ""), options),
		)
		.join("");
}

function cleanLegacySources({ home, fsImpl, now }) {
	const legacy = path.join(home, ".config", "hypr", "hyprland.conf");
	if (!fsImpl.existsSync(legacy)) {
		return { name: "legacy source cleanup", status: "already done" };
	}
	const monitorsConf = path.join(home, ".config", "hypr", "monitors.conf");
	const stripMonitorsConf =
		!fsImpl.existsSync(monitorsConf) ||
		!isHyprmoncfgOwned(fsImpl, monitorsConf);
	const original = fsImpl.readFileSync(legacy, "utf8");
	const cleaned = withoutRetiredSources(original, { stripMonitorsConf });
	if (cleaned === original) {
		return { name: "legacy source cleanup", status: "already done" };
	}
	const { backup, timestamp, mode } = backupFile(fsImpl, legacy, now);
	writeAtomically(fsImpl, legacy, cleaned, timestamp, mode);
	return { name: "legacy source cleanup", status: "applied", backup };
}

const HYPRMONCFG_MARKERS = new Set([
	"# Generated by hyprmoncfg",
	"-- Generated by hyprmoncfg",
]);

function isHyprmoncfgOwned(fsImpl, file) {
	const content = fsImpl.readFileSync(file, "utf8").replace(/^\uFEFF/, "");
	const firstLine = content.split(/\r\n|\r|\n/, 1)[0];
	return HYPRMONCFG_MARKERS.has(firstLine);
}

function removeOrphans({ home, fsImpl, now }) {
	const hypr = path.join(home, ".config", "hypr");
	const files = [
		path.join(hypr, "haoshoku-bindings.conf"),
		path.join(hypr, "haoshoku-workspaces.conf"),
		path.join(hypr, "monitors.conf"),
	].map((file) => {
		if (!fsImpl.existsSync(file)) return { path: file, status: "already done" };
		if (
			path.basename(file) === "monitors.conf" &&
			isHyprmoncfgOwned(fsImpl, file)
		) {
			return {
				path: file,
				status: "already done",
				reason: "hyprmoncfg-owned",
			};
		}
		const { backup } = backupFile(fsImpl, file, now);
		fsImpl.unlinkSync(file);
		return { path: file, status: "applied", backup };
	});
	return {
		name: "orphan cleanup",
		status: files.some((file) => file.status === "applied")
			? "applied"
			: "already done",
		files,
	};
}

const LEGACY_THEME_PATH = "~/.config/omarchy/current";
const QUATTRO_THEME_PATH = "~/.local/state/omarchy/current";
const STOCK_MONITORS_LUA = `-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
-- List current monitors and supported resolutions with: hyprctl monitors all

local omarchy_gdk_scale = 2
local omarchy_monitor_scale = "auto"

hl.env("GDK_SCALE", tostring(omarchy_gdk_scale))
hl.monitor({ output = "", mode = "preferred", position = "auto", scale = omarchy_monitor_scale })

-- Configure a specific monitor.
-- hl.monitor({ output = "DP-2", mode = "2560x1440@144", position = "0x0", scale = 1 })

-- Portrait/rotated secondary monitor (transform: 1 = 90°, 3 = 270°).
-- hl.monitor({ output = "DP-2", mode = "preferred", position = "auto", scale = 1, transform = 1 })
`;

function rewriteLiveThemePaths({ home, fsImpl, now }) {
	const files = [
		path.join(home, ".config", "fish", "config.fish"),
		path.join(home, ".config", "kitty", "haki.session"),
		path.join(home, ".config", "kitty", "agents.session"),
	].map((file) => {
		if (!fsImpl.existsSync(file)) return { path: file, status: "already done" };
		const original = fsImpl.readFileSync(file, "utf8");
		const desired = original.replaceAll(LEGACY_THEME_PATH, QUATTRO_THEME_PATH);
		if (desired === original) return { path: file, status: "already done" };
		const { backup, timestamp, mode } = backupFile(fsImpl, file, now);
		writeAtomically(fsImpl, file, desired, timestamp, mode);
		return { path: file, status: "applied", backup };
	});
	return {
		name: "live theme paths",
		status: files.some((file) => file.status === "applied")
			? "applied"
			: "already done",
		files,
	};
}

function identicalBackup(fsImpl, file, contents) {
	const directory = path.dirname(file);
	if (!fsImpl.existsSync(directory)) return null;
	const prefix = `${path.basename(file)}.bak.`;
	for (const candidate of fsImpl.readdirSync(directory)) {
		if (!candidate.startsWith(prefix)) continue;
		const backup = path.join(directory, candidate);
		if (fsImpl.readFileSync(backup).equals(contents)) return backup;
	}
	return null;
}

function handoffMonitorsLua({ home, fsImpl, now, logImpl, hyprmoncfg }) {
	const monitors = path.join(home, ".config", "hypr", "monitors.lua");
	const exists = fsImpl.existsSync(monitors);
	if (exists && isHyprmoncfgOwned(fsImpl, monitors)) {
		return {
			name: "monitors.lua ownership handoff",
			status: "already done",
		};
	}

	const ready =
		hyprmoncfg?.packageReady === true &&
		hyprmoncfg?.serviceEnabled === true;
	if (!ready) {
		if (!exists) {
			const backup = identicalBackup(
				fsImpl,
				monitors,
				Buffer.from(STOCK_MONITORS_LUA),
			);
			if (backup) {
				const timestamp = now();
				const mode = fsImpl.statSync(backup).mode & 0o777;
				writeAtomically(
					fsImpl,
					monitors,
					fsImpl.readFileSync(backup),
					timestamp,
					mode,
				);
				const message = `manual attention: hyprmoncfg is not ready; restored missing ${monitors} from ${backup}.`;
				logImpl.warning(message);
				return {
					name: "monitors.lua ownership handoff",
					status: "manual attention",
					restoredFrom: backup,
					message,
				};
			}
		}
		const message = exists
			? `manual attention: hyprmoncfg is not ready; left ${monitors} untouched.`
			: `manual attention: hyprmoncfg is not ready and ${monitors} is missing; no migration stock backup was found to restore.`;
		logImpl.warning(message);
		return {
			name: "monitors.lua ownership handoff",
			status: "manual attention",
			message,
		};
	}

	if (!exists) {
		const backup = identicalBackup(
			fsImpl,
			monitors,
			Buffer.from(STOCK_MONITORS_LUA),
		);
		if (backup) {
			const timestamp = now();
			const mode = fsImpl.statSync(backup).mode & 0o777;
			writeAtomically(
				fsImpl,
				monitors,
				fsImpl.readFileSync(backup),
				timestamp,
				mode,
			);
			const message = `manual attention: restored missing ${monitors} from ${backup}; verify hyprmoncfg ownership before removing it again.`;
			logImpl.warning(message);
			return {
				name: "monitors.lua ownership handoff",
				status: "manual attention",
				restoredFrom: backup,
				message,
			};
		}
		const message = `manual attention: ${monitors} is missing and no migration stock backup was found; restore a valid file before reloading Hyprland.`;
		logImpl.warning(message);
		return {
			name: "monitors.lua ownership handoff",
			status: "manual attention",
			message,
		};
	}

	const contents = fsImpl.readFileSync(monitors);
	if (contents.equals(Buffer.from(STOCK_MONITORS_LUA))) {
		const { backup } = backupFile(fsImpl, monitors, now);
		fsImpl.unlinkSync(monitors);
		logImpl.success(
			`Handed ${monitors} to hyprmoncfg; stock configuration backed up at ${backup}.`,
		);
		return {
			name: "monitors.lua ownership handoff",
			status: "applied",
			backup,
		};
	}

	let backup = identicalBackup(fsImpl, monitors, contents);
	if (!backup) backup = backupFile(fsImpl, monitors, now).backup;
	const message = `manual attention: customized ${monitors} remains in place; hyprmoncfg will refuse to manage monitors until it is reconciled or removed.`;
	logImpl.warning(message);
	return {
		name: "monitors.lua ownership handoff",
		status: "manual attention",
		backup,
		message,
	};
}

async function waitForMonitorsLua({
	monitors,
	fsImpl,
	sleepImpl,
	pollIntervalMs,
	pollTimeoutMs,
}) {
	if (fsImpl.existsSync(monitors) && isHyprmoncfgOwned(fsImpl, monitors))
		return true;
	for (
		let elapsed = 0;
		elapsed < pollTimeoutMs;
		elapsed += pollIntervalMs
	) {
		await sleepImpl(pollIntervalMs);
		if (fsImpl.existsSync(monitors) && isHyprmoncfgOwned(fsImpl, monitors))
			return true;
	}
	return false;
}

function quattroShimIsActive(home, fsImpl) {
	const state = path.join(home, ".local", "state", "omarchy");
	const shareLink = path.join(home, ".local", "share", "omarchy");
	const linkState = fsImpl.lstatSync(shareLink, { throwIfNoEntry: false });
	if (!linkState?.isSymbolicLink()) return false;
	const target = path.resolve(
		path.dirname(shareLink),
		fsImpl.readlinkSync(shareLink),
	);
	return (
		target === path.join(state, "upgrade-to-quattro-live-omarchy") &&
		fsImpl.existsSync(path.join(state, "upgrade-to-quattro-hypr-defaults")) &&
		fsImpl.existsSync(
			path.join(
				home,
				".config",
				"omarchy",
				"hooks",
				"post-boot.d",
				"cleanup-upgrade-to-quattro-live-shim",
			),
		) &&
		fsImpl.existsSync(path.join(home, ".config", "hypr", "hyprland.conf"))
	);
}

export async function migrateOmarchy3To4({
	home = homedir(),
	fsImpl = fs,
	now = Date.now,
	env = process.env,
	captureCommandImpl = runCommandCapture,
	runCommandImpl = runCommand,
	logImpl = log,
	configureOmarchyWorkspacesImpl = configureOmarchyWorkspaces,
	configureHyprmoncfgImpl = configureHyprmoncfg,
	configureOmarchyPluginsImpl = configureOmarchyPlugins,
	sleepImpl = (milliseconds) => new Promise((resolve) => setTimeout(resolve, milliseconds)),
	pollIntervalMs = 100,
	pollTimeoutMs = 3000,
} = {}) {
	let version;
	try {
		version = await captureCommandImpl("omarchy version", {
			env: { ...env, OMARCHY_PATH: "/usr/share/omarchy" },
		});
	} catch {
		version = null;
	}
	const gate = await checkOmarchyV4({ versionResult: version, logImpl });
	if (!gate.ok) {
		return {
			status: "refused",
			steps: [
				{ name: "version gate", status: "refused", message: gate.message },
			],
		};
	}
	const major = gate.major;
	const laptopFollowUp =
		"On a laptop, save a laptop hyprmoncfg profile and run --hyprmoncfg-backup.";
	const baseRecoveryInstruction =
		"remove the appended require lines from hyprland.lua, then reboot";
	const versionStep = { name: "version gate", status: "clean", major };
	if (quattroShimIsActive(home, fsImpl)) {
		const deferred = {
			name: "Quattro live shim",
			status: "deferred",
			message:
				"The Quattro live compatibility shim is still active; reboot, then re-run this migration.",
		};
		logImpl.warning(deferred.message);
		return {
			status: "deferred",
			steps: [versionStep, deferred],
			manualAuthChecklist: [],
			laptopFollowUp,
			recoveryInstruction: baseRecoveryInstruction,
		};
	}

	const steps = [
		versionStep,
		cleanLegacySources({ home, fsImpl, now }),
		removeOrphans({ home, fsImpl, now }),
		rewriteLiveThemePaths({ home, fsImpl, now }),
	];
	let recoveryInstruction = baseRecoveryInstruction;

	let workspaces;
	let hyprmoncfg;
	let deployFailure = null;
	try {
		workspaces =
			(await configureOmarchyWorkspacesImpl({
				home,
				fsImpl,
				now,
				env,
				captureCommandImpl,
				runCommandImpl,
				logImpl,
				versionResult: version,
			})) ?? {};
	} catch (error) {
		const message = `Workspace deployment failed: ${error instanceof Error ? error.message : String(error)}`;
		workspaces = { status: "failed", message };
		hyprmoncfg = {
			status: "skipped",
			message: "Skipped because workspace deployment failed.",
		};
		deployFailure = message;
	}
	if (!deployFailure) {
		try {
			hyprmoncfg =
				(await configureHyprmoncfgImpl({
					home,
					fsImpl,
					now,
					env,
					captureCommandImpl,
					logImpl,
					versionResult: version,
				})) ?? {};
		} catch (error) {
			const message = `hyprmoncfg deployment failed: ${error instanceof Error ? error.message : String(error)}`;
			hyprmoncfg = { status: "failed", message };
			deployFailure = message;
		}
	}
	if (deployFailure) {
		logImpl.error(deployFailure);
		logImpl.info(recoveryInstruction);
		steps.push({
			name: "deploy reusable config",
			status: "failed",
			workspaces,
			hyprmoncfg,
			message: deployFailure,
		});
		steps.push({
			name: "plugins",
			status: "skipped",
			message: "Skipped because reusable configuration deployment failed.",
		});
		steps.push({
			name: "validate and hand off",
			status: "skipped",
			message:
				"Skipped because reusable configuration deployment failed; Hyprland was not reloaded.",
		});
		return {
			status: "failed",
			steps,
			manualAuthChecklist: [],
			laptopFollowUp,
			recoveryInstruction,
		};
	}
	const unreadyHyprmoncfgParts = [];
	if (hyprmoncfg.packageReady !== true) unreadyHyprmoncfgParts.push("package");
	if (hyprmoncfg.serviceEnabled !== true)
		unreadyHyprmoncfgParts.push("service");
	const deployStep = {
		name: "deploy reusable config",
		status:
			unreadyHyprmoncfgParts.length > 0 || workspaces.status === "refused"
				? "manual attention"
				: Object.values(workspaces).some((value) => value === true) ||
						Number(hyprmoncfg.deployed) > 0
					? "applied"
					: "already done",
		workspaces,
		hyprmoncfg,
	};
	if (unreadyHyprmoncfgParts.length > 0) {
		deployStep.message = `hyprmoncfg ${unreadyHyprmoncfgParts.join(" and ")} ${unreadyHyprmoncfgParts.length === 1 ? "is" : "are"} not ready; complete installation/service setup and re-run.`;
		logImpl.warning(deployStep.message);
	} else if (workspaces.status === "refused") {
		deployStep.message = workspaces.message;
		logImpl.warning(deployStep.message);
	}
	steps.push(deployStep);

	const handoff = handoffMonitorsLua({
		home,
		fsImpl,
		now,
		logImpl,
		hyprmoncfg,
	});
	steps.push(handoff);
	if (handoff.status === "applied") {
		recoveryInstruction = `${baseRecoveryInstruction}; if monitors.lua is missing or Hyprland cannot load, restore ${path.join(home, ".config", "hypr", "monitors.lua")} from ${handoff.backup}`;
	}
	logImpl.info(recoveryInstruction);

	const monitors = path.join(home, ".config", "hypr", "monitors.lua");
	let regeneration;
	if (handoff.status === "applied") {
		const regenerated = await waitForMonitorsLua({
			monitors,
			fsImpl,
			sleepImpl,
			pollIntervalMs,
			pollTimeoutMs,
		});
		if (regenerated) {
			regeneration = {
				name: "monitors.lua regeneration",
				status: "clean",
			};
		} else {
			const timestamp = now();
			const mode = fsImpl.statSync(handoff.backup).mode & 0o777;
			writeAtomically(
				fsImpl,
				monitors,
				fsImpl.readFileSync(handoff.backup),
				timestamp,
				mode,
			);
			regeneration = {
				name: "monitors.lua regeneration",
				status: "manual attention",
				restoredFrom: handoff.backup,
				message: `hyprmoncfg did not regenerate ${monitors} within ${pollTimeoutMs}ms; restored the stock file from ${handoff.backup}.`,
			};
			logImpl.warning(regeneration.message);
		}
		steps.push(regeneration);
	}

	let plugins;
	try {
		plugins =
			(await configureOmarchyPluginsImpl({
				logImpl,
				env,
				versionResult: version,
			})) ?? {};
	} catch (error) {
		const message = `Plugin deployment failed: ${error instanceof Error ? error.message : String(error)}`;
		logImpl.error(message);
		steps.push({ name: "plugins", status: "failed", message });
		steps.push({
			name: "validate and hand off",
			status: "skipped",
			message:
				"Skipped because plugin deployment failed; Hyprland was not reloaded.",
		});
		return {
			status: "failed",
			steps,
			manualAuthChecklist: [],
			laptopFollowUp,
			recoveryInstruction,
		};
	}
	steps.push({
		name: "plugins",
		status:
			plugins.failed?.length > 0
				? "manual attention"
				: plugins.installed?.length > 0 || plugins.enabled?.length > 0
					? "applied"
					: "already done",
		result: plugins,
	});

	let validation;
	const validationBlockers = [];
	if (workspaces.status === "refused") {
		validationBlockers.push("workspace deployment was refused");
	}
	if (!fsImpl.existsSync(monitors)) {
		validationBlockers.push(`${monitors} is missing`);
	}
	if (regeneration?.status === "manual attention") {
		validationBlockers.push(regeneration.message);
	}
	if (validationBlockers.length > 0) {
		validation = {
			name: "validate and hand off",
			status: "skipped",
			message: `${validationBlockers.join("; ")}. Hyprland validation was skipped to avoid reloading an unsafe configuration.`,
		};
	} else {
		const reloaded = await runCommandImpl("hyprctl reload", { check: false });
		const configErrors = await captureCommandImpl("hyprctl configerrors");
		const clean =
			reloaded === true &&
			configErrors?.exitCode === 0 &&
			configErrors.failed === false &&
			String(configErrors.stdout).trim() === "";
		validation = {
			name: "validate and hand off",
			status: clean ? "clean" : "failed",
			reloaded,
			configErrors,
		};
		if (clean) logImpl.success("Hyprland reloaded with no config errors.");
		else
			logImpl.error(
				"Hyprland validation failed; inspect the captured configerrors output before continuing.",
			);
	}
	steps.push(validation);

	const manualAuthChecklist = plugins.manualAuthChecklist ?? [];
	if (manualAuthChecklist.length > 0) {
		logImpl.info("Omarchy plugin manual-auth checklist:");
		for (const item of manualAuthChecklist) {
			logImpl.info(`  - ${item.id}: ${item.requirement}`);
		}
	}
	logImpl.info(laptopFollowUp);

	const status =
		validation.status === "failed"
				? "failed"
				: steps.some((step) => step.status === "manual attention")
					? "manual attention"
					: "completed";
	return {
		status,
		steps,
		manualAuthChecklist,
		laptopFollowUp,
		recoveryInstruction,
	};
}
